### ISSUE TITLE
Consider adding further exceptions to submit() 

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#10]
... in order to distinguish between EAGAIN types of errors and others.

**Comment by hategan** [comment]
Question for @andre-merzky and @SteVwonder:

do we think:
a. `InvalidJobException` can have EAGAIN subtypes?
   - perhaps related: would a "too many jobs in the queue" error be an `InvalidJobException` or a `SubmitException`?
b. `SubmitException` can have EAGAIN subtypes?

**Comment by andre-merzky** [comment]
> do we think:
> a. `InvalidJobException` can have EAGAIN subtypes?
> 
>     * perhaps related: would a "too many jobs in the queue" error be an `InvalidJobException` or a `SubmitException`?

I would argue that `EAGAIN` should be the decision criteria on `InvalidJobException` vs. `SubmitException`: an invalid job will remain invalid and trying again will not change that.  For example: if a job requests a node type which does not exist on the target machine, then that is invalid, but `too many jobs in the queue` can apply for a perfectly valid job, it just happens that the job cannot be submitted right now because of policy issues.

> 
> b. `SubmitException` can have EAGAIN subtypes?

Yes, I would expect so.  I can imagine cases where that job would fail again and again, for example if the queues are in maintenance or the user's allocation expired and the scheduler refuses the job because of this - but even then, the submission *would* succeed when the queues are up again or on allocation renewal (meaning, the actual job request is valid).

My $0.02, Andre.

**Comment by hategan** [comment]
Ok, so if I understand @andre-merzky correctly, `InvalidJobException` is "fatal" and `SubmitException` should have a `isTransient()` method. Yes?

I'd be cool with that.

**Comment by andre-merzky** [comment]
> Ok, so if I understand @andre-merzky correctly, `InvalidJobException` is "fatal" and `SubmitException` should have a `isTransient()` method. Yes?
> 
> I'd be cool with that.

Essentially yes, that would work for me.

**Comment by SteVwonder** [comment]
Sounds good to me!

**Comment by andre-merzky** [comment]
This is now well defined in the spec - closing.
