### ISSUE TITLE
Add a get_version method/function 

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#11]
Add a note about version obj vs string depending on programming  language

**Comment by hategan** [comment]
`JobExecutor.getVersion()`, returning a `Version` object has the following description:

> Returns the version of this executor. If the system/language/standard library in which the library is implemented provides a specific versioning mechanism and/or versioning class, it should be used as the Version class. If such a class is not provided, implementations can use a simple string type for the version.

Does that address this issue?

**Comment by andre-merzky** [comment]
Sounds good to me, thanks!

**Comment by hategan** [comment]
@andre-merzky did you mean to close the conversation or the issue?
