### ISSUE TITLE
Interface Specification: Ensure python snippets are available for interfaces with major diff between languages

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/job-api-spec#117]
**Is your request related to a problem? Please describe.**
Only some of the constructors/methods/etc have their python defintions

**Describe the solution you'd like**
Ensure that we have a python definition for every interface/constructor/method etc

**Comment by andre-merzky** [comment]
> Only some of the constructors/methods/etc have their python defintions

my understanding is that the Java/Python tabs are supposed to be applied to example code, not necessarily for the specification parts (those are all Java now - but see #71 for discussion on SDL).    I found one snippet where the tab was missing - that should be addressed in #123 now.

But maybe I am missing the point and you refer to the two entries which do specify python bindings (constructors for `JobSpec` and `ResourceSpec`?   I am not convinced that this is the right way to specify the language binding actually, and still would prefer a (small) separate document which also gives room to discuss general issues (name space, exception handling, datetime types, etc.).

**Comment by SteVwonder** [comment]
Ah! I had come to a different conclusion from #71 and our phone calls.  I was under the impression that we were using the tabs in lieu of separate docs for now.  So maybe we have some more discussion to do over in #71.

Seems reasonable for the alpha release to have this issue be what you describe - making sure every example has a python version and leave the python specific definitions be resolved in #71.

**Comment by hategan** [comment]
> my understanding is that the Java/Python tabs are supposed to be applied to example code, not necessarily for the specification parts

I think it would be good to have the spec parts follow that same idea so that somebody reading the spec with a certain language in mind does not have to switch between docs all the time.

I think I wanted to take concrete steps in that direction and I remember a conversation about it, but I have not had time yet to do it.

**Comment by andre-merzky** [comment]
> I think it would be good to have the spec parts follow that same idea so that somebody reading the spec with a certain language in mind does not have to switch between docs all the time.

I don't think this is a good idea, really.  As said above, I think that most of the language binding differences will be text: what do exceptions inherit from, what are rendered as attributes vs. methods, what types are used why, etc.  Assuming we ever want to add a 2nd language, this will be really messy.

A Python specific document should have less than two pages explaining those items, and about a page of skeleton classes - I don't think this would be a burden.

Either way, this PR only tackles the examples, not the spec parts.

**Comment by andre-merzky** [comment]
PS.: re-reading #71, I probably misinterpreted that discussion:  I assumed SDL-like (or whatever) for the spec parts, language tabs for examples.  The text indeed implies different, sorry for causing confusion.  So that's another topic for Friday's call I guess... ;-)

**Comment by hategan** [comment]
> I don't think this is a good idea, really. As said above, I think that most of the language binding differences will be text: what do exceptions inherit from, what are rendered as attributes vs. methods, what types are used why, etc. Assuming we ever want to add a 2nd language, this will be really messy.

Agreed. 

I was mostly referring to language specific methods/constructors. In C++, you can overload methods, so if C++ was selected, you should see the set of all overloaded methods with a given name. By contrast, in Python you'd want a single method with keyword args.

So I think the above is both convenient and doable with tabs.

This isn't strictly necessary. Translating overloaded signatures to keyword signatures is a deterministic process, so we could simply specify how it's done. But then, a similar thing applies to examples: they could be translated by the user. So these tabs are a matter of convenience as far as I can tell.
