### ISSUE TITLE
Remove mentions of the native id from JobStatus.getMetadata()

### ISSUE THREAD

**Issue by hategan** [ExaWorks/job-api-spec#126]
**Is your request related to a problem? Please describe.**

There's a mention of the native ID being passed back through state changes as part of the metadata in a JobStatus object. This was at a time when list()/attach()/ and the native_id property was not part of the spec. However, those have been merged (or are close to being so), so there is a persistent native ID property. making the native ID metadata attribute superfluous.

**Describe the solution you'd like**
Remove mentions of the native ID from JobStatus.getMetadata()

**Comment by andre-merzky** [comment]
I agree with that request.
