### ISSUE TITLE
 think more about env var expansion in arguments and other places. 

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#13]
The important issue is how much of a burden this is on implementations if we mandate it.

**Comment by jameshcorbett** [comment]
I don't see it as much of a burden, but I don't see much of a benefit either. What does it allow that a user couldn't do themselves, without too much trouble? For instance, in Python, users could pretty easily use `os.path.expandvars` to perform the expansion, or something like `jobspec.environ = "/my/app/" + os.pathsep + os.getenv("PATH")`. The easier it is to do, the less burden on the implementer, but the less burden on the user if it is left out, too.

I think environment variable expansion should not be supported at all. I know plenty of libraries and workflow managers that don't support environment variable expansion. Furthermore, it also introduces complications arising from ordering, like @andre-merzky  mentioned [here](https://github.com/ExaWorks/job-api-spec/pull/50#discussion_r541797982). If we let users do their own environment-variable expansion, they can figure out those issues to their own satisfaction. Second, there could be instances where users actually don't want environment variable expansion. In cases like these, I think it is better to let users figure it out for themselves.

**Comment by hategan** [comment]
> For instance, in Python, users could pretty easily use `os.path.expandvars` to perform the expansion,

This expansion refers to expansion on the compute node side. In other words, the environment variables that are being expanded may not be defined on the client side or they may have different values than on the client side. The user could have a pre_launch or wrapper script for this purpose, but the question is whether installing such wrapper scripts is a reasonable thing to ask the user to do in order to, say, add some directory to $PATH or figure out where $SCRATCH is.

**Comment by jameshcorbett** [comment]
Ah OK I didn't see that anywhere in the discussion---it is spread out over many issues and PRs. That is more reasonable. So the use-case is that you don't want to override the Job's environment, you just want to add one or two things to whatever the default environment is on the target machine.

In that case I agree with Andre when [he said](https://github.com/ExaWorks/job-api-spec/issues/54#issuecomment-731845685)

> > ```
> > * if a user needs to do PATH=/path/to/my/app:$PATH, should it be required that a pre- script be used?
> > ```
> 
> 
> Yes

You mentioned "figuring out where $SCRATCH is". But isn't that what `inheritEnvironment=True` is for? The environment-variable expansion seems like it is for something else---where you want to extend an environment variable that will exist on the target machine---not for just inheriting environment variables that will exist on the target machine.

**Comment by hategan** [comment]
> In that case I agree with Andre when [he said](https://github.com/ExaWorks/job-api-spec/issues/54#issuecomment-731845685)
> 
> > > ```
> > > * if a user needs to do PATH=/path/to/my/app:$PATH, should it be required that a pre- script be used?
> > > ```
> > 
> > 
> > Yes

That was when we were specifying pre-scripts as lists of strings. We've come to a different understanding in the mean time, which is that pre-scipts are paths to some script and simple things like the PATH example stays in the job spec.

> 
> You mentioned "figuring out where $SCRATCH is". But isn't that what `inheritEnvironment=True` is for? The environment-variable expansion seems like it is for something else---where you want to extend an environment variable that will exist on the target machine---not for just inheriting environment variables that will exist on the target machine.

See "... in arguments" in the issue title?

If I have some legacy app that expects a temp dir on the command line, I should be able to easily pass $SCRATCH to it. To give you a more intuitive view of this, you'd likely, in a PBS submit script, write:

```sh
legacy_app ... -tmpdir=$SCRATCH
```

The meaning of $SCRATCH there is that it will be expanded when the launch command is executed, which is on the service/rank 0 node. We want users to be able to easily do things with PSI/J that they were able to do before with submit scripts.

**Comment by jameshcorbett** [comment]
> We've come to a different understanding in the mean time.

Great. If you have a link that would be great, I would like to see the thought process. (I am wondering why pre-scripts themselves can't have arguments.) But it seems reasonable either way.

> See "... in arguments" in the issue title?

Yes. But I also see "and other places." And your example wasn't clear. 

> We want users to be able to easily do things with PSI/J that they were able to do before with submit scripts.

Users could just wrap `legacy_app` in a script that accessed `SCRATCH` and passed the value on to `legacy_app`---that is what I assume J/PSI implementations will just do themselves. But that is asking substantially more of users.

**Comment by hategan** [comment]
> [...] (I am wondering why pre-scripts themselves can't have arguments.) [...]

Simplicity. They can be added if there is a compelling argument.

> [...] 
> > We want users to be able to easily do things with PSI/J that they were able to do before with submit scripts.
> 
> Users could just wrap `legacy_app` in a script that accessed `SCRATCH` and passed the value on to `legacy_app`---that is what I assume J/PSI implementations will just do themselves. But that is asking substantially more of users.

"Just" just doesn't mean what it's typically used for. The first "just" above involves writing a script and copying it to every cluster you intend to run things on when you could just say "$SCRATCH" in the spec instead. You'd probably agree that the latter "just" is significantly more just than the former.

**Comment by hategan** [comment]
The cost vs benefit ratio may be a bit high without some compelling use cases.

We can change things in the future if needed.
