### ISSUE TITLE
Python: `JobExecutor.close()`

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#130]
Should we provide a `close()` call on the `JobExecutor`, to signal the connector that resources can be freed? That's seems specifically useful if the connector commuinicates to an external service of some kind.  `__del__` cannot really be used for that as it interferes with Python's garbage collection.

**Comment by hategan** [comment]
Using __del__ is fine. It gets called when the object is garbage collected. The implementation should make sure to call the super().__del__, but otherwise I see not problem overriding this.

Is there a concrete case where close() is needed so that we can look at whether there might be alternative solutions before adding a new method? I'm worried that manual lifecycle management leading to increased complexity of using the API.

**Comment by andre-merzky** [comment]
(markup is interfering - but I assume you mean `__del__()`, not `del()`)

I had to read up on the GC again - and some behavior changed indeed, at least the objects get garbage collected now.  This one remains though:
```
It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits.
```

It might not be much of an issue in real code (outside of simple examples) though.

> I'm worried that manual lifecycle management leading to increased complexity of using the API.

I am worried about that also.


> Is there a concrete case where close() is needed so that we can look at whether there might be alternative solutions before adding a new method? 

This is specifically aimed at backends which consume resources on the client side.  RP happens to be such one: it creates a number of processes and communication channels on the client side.  If `__del__` is reliably called in the connector, than that's not an issue.  I'll have another look into this.

**Comment by hategan** [comment]
Sorry for the markup issue. Yes, \_\_del\_\_.

If the resources in question get freed at process shutdown, it probably doesn't matter that \_\_del\_\_ is not reliably called.

If it's server resources, I'd argue the server should be re-designed to not leak if a client does not gracefully disconnect. That said,  connector instances can also add shutdown hooks to ensure that proper cleanup, if necessary, is done at process shutdown.

So I think, given that reasonable and not terribly difficult solutions exist for the problem, the addition of a method to JobExecutor may not be warranted.

**Comment by hategan** [comment]
@andre-merzky, can we move forward with this (close/hammer more)?

**Comment by andre-merzky** [comment]
I don't see a need to act on this one until we see actual problematic behavior.  The improvements to the GC seem to address most of my concerns anyway.  Thanks for the ping - closing.
