### ISSUE TITLE
Python: `wait()` default arguments

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#135]
The specification allows
```py
job.wait(timeout, states)
job.wait(timeout)
job.wait(states)
job.wait()
```

It is not common in Python to overload method signatures based on type.  I don't mind doing the above though and find it useful, but still wanted to raise the  question if this is what we want in the python bindings.

FWIW, if we have to decide on an order, I have a weak preference for `states` first, allowing for `job.wait(CANCELED)`.

**Comment by andre-merzky** [comment]
> Agreed that we can't achieve that example exactly

Well, technically we could achieve it:
```py
>>> def wait(states=None, timeout=None):
...     if states and not timeout and isinstance(states, (int, float)):
...         timeout = states
...         timeout = states
...         states = None
...     print(f'states: {states}, timeout: {timeout}')

>>> wait('NEW')
states: NEW, timeout: None

>>> wait(1.0)
states: None, timeout: 1.0

>>> wait('NEW', 1.0)
states: NEW, timeout: 1.0
```

but I am not sure how you guys think about that...

**Comment by hategan** [comment]
I think it's fine to use types to infer what the arguments are in order to simulate multiple dispatch, especially when we expect all forms to be used in roughly equal measure.

**Comment by andre-merzky** [comment]
FWIW, we use that in very few cases in our APIs (mostly where we changed the arg order and wanted to maintain backward compatibility), and that so far works w/o any problems.  OTOH, it will likely make type hinting a bit less useful for those signatures (`states` now needs to be an `Optional[Union[List[StateEnum], float]]` or something like this).

**Comment by hategan** [comment]
> t will likely make type hinting a bit less useful

That's a good point.

An alternative would be to use keyword arguments wisely. Such as `wait(states: Optional[List[JobState]] = None, timeout: Optional[Union[timeinterval, int, float]] = None)`. While this doesn't allow calling it in all positional scenarios above, I think it fulfills the spirit of what the spec intends.

**Comment by hategan** [comment]
I think what we have turned out to be OK. @andre-merzky, should we close this?

**Comment by andre-merzky** [comment]
Yes, I agree.
