### ISSUE TITLE
pre/post/executable paths are over-prescriptive 

### ISSUE THREAD

**Issue by frobnitzem** [ExaWorks/job-api-spec#175]
**Is your request related to a problem? Please describe.**
First, a bug: the PreLaunch and PostLaunch arguments are not mentioned in the [JobSpec constructor](https://github.com/ExaWorks/job-api-spec/blob/main/specification.md#jobspec).

Second, the specification of paths inside the JobSpec is also not in the spirit of an API - which should rely on "agreed upon" system-specific paths as little as possible.  File contents would be preferable.  IMHO, at present job specs are likely to be used in practice as "executable=/bin/bash", "args=-c,'contents of script here'".

More importantly, however, is that the JobSpec prescribes a particular execution sequence:
1. batch job begins
2. pre_launch script is run (no parameters)
3. launcher launches executable (presumably in parallel)
4. post_launch script is run (no parameters)

Instead, my typical workflow is:
1. pre_launch script is run (templated with job-specific variables) on a login node.  It sets up the job working directory by copying files, loading modules, etc. If this fails, I want to know immediately.
2. batch job begins
3. my job script prints some diagnostic information (node names, etc.) and then launches one or many executables (in parallel).
4. my job script may do post_launch operations like copying out result files.  These would be better to execute on the login node, but capturing the notification of job completion is difficult.

**Describe the solution you'd like**
- replace pre_launch and post_launch with strings which will be written to files.  pre_launch should execute on the login node before job submission - blocking job submission if unsuccessful.
- replace executable and arguments with a templated script (of any sort, it can specify its own `#!/usr/bin/env ...` header).
- run the executable directly in the job, since the parallel "launcher" can be a template parameter like "{{mpirun}}", which expands to the appropriate "srun -n5 -c7", etc.

The last point, exposing the job templating mechanism to the user, is critical because it prevents messy work-arounds.  It also nicely supports multi-step jobs.

**Comment by hategan** [comment]
> **Is your request related to a problem? Please describe.** First, a bug: the PreLaunch and PostLaunch arguments are not mentioned in the [JobSpec constructor](https://github.com/ExaWorks/job-api-spec/blob/main/specification.md#jobspec).

Ah, thank you. Will add.

> 
> Second, the specification of paths inside the JobSpec is also not in the spirit of an API - which should rely on "agreed upon" system-specific paths as little as possible.

I am not entirely sure what you mean there.

> File contents would be preferable. IMHO, at present job specs are likely to be used in practice as "executable=/bin/bash", "args=-c,'contents of script here'".

The main purpose of PSI/J is to provide an abstraction layer to job execution systems of all kinds for higher level tools, such as workflow systems. In my experience, those overwhelmingly employ structured entities rather than free-form strings. There is also a practical reason why we try to avoid script contents in the specification, and that is the nightmare that is quoting and escaping in multiple layers of shell scripts.

> 
> More importantly, however, is that the JobSpec prescribes a particular execution sequence:
> 
> 1. batch job begins
> 2. pre_launch script is run (no parameters)

Not quite. The pre and post launch scripts have access to the environment variables of the job. So they can be parametrized.

> 3. launcher launches executable (presumably in parallel)
> 4. post_launch script is run (no parameters)

I wouldn't quite say it that way. Pre- and post- launch are there to allow a job to set things up on the job lead node (aka, rank 0 node), such as `module load xyz`, which should not be done on all the compute nodes of a job.

> 
> Instead, my typical workflow is:
> 
> 1. pre_launch script is run (templated with job-specific variables) on a login node.  It sets up the job working directory by copying files, loading modules, etc. If this fails, I want to know immediately.

I don't think PSI/J prevents that. One can always run local jobs on the login node prior to submitting a batch job and/or after. So I think that perhaps the names pre_launch and post_launch may be a source of confusion, but "launch" here refers to the specific step of starting all the ranks of a job once its resources are allocated (aka, running mpirun/srun/ibrun etc.).

> 2. batch job begins
> 3. my job script prints some diagnostic information (node names, etc.) and then launches one or many executables (in parallel).
> 4. my job script may do post_launch operations like copying out result files.  These would be better to execute on the login node, but capturing the notification of job completion is difficult.
> 
> **Describe the solution you'd like**
> 
> * replace pre_launch and post_launch with strings which will be written to files.  pre_launch should execute on the login node before job submission - blocking job submission if unsuccessful.

See above. We'll still need tools to allow injecting commands after the job resources were allocated but before the job is launched on all the nodes. And it is entirely possible to run what you seek without any modifications.

> * replace executable and arguments with a templated script (of any sort, it can specify its own `#!/usr/bin/env ...` header).

Also see above, but this would imply less structure without much added benefit since one can always generate a script of any form outside of PSI/J and then use it as an executable in the JobSpec.

> * run the executable directly in the job, since the parallel "launcher" can be a template parameter like "{{mpirun}}", which expands to the appropriate "srun -n5 -c7", etc.

While this is a possibility, the way that srun is invoked (i.e., whether directly in the job script or through another script) is largely a matter of the implementation. The reason for wrapper scripts around srun/mpirun/etc in psij-python is mostly because it simplifies the implementation and aids in debugging (the job invocation, launcher and all, is a one-liner that can be invoked manually if troubleshooting is needed).

> 
> The last point, exposing the job templating mechanism to the user, is critical because it prevents messy work-arounds. It also nicely supports multi-step jobs.

Perhaps I'm not understanding this well, but I don't quite see what the benefit is here or why the templating cannot be done outside of PSI/J if needed.

I think there are some great scenarios here, and it may be useful to explore them further and at least add some examples of one could tackle them with PSI/J.

**Comment by frobnitzem** [comment]
> > Second, the specification of paths inside the JobSpec is also not in the spirit of an API - which should rely on "agreed upon" system-specific paths as little as possible.
>
> I am not entirely sure what you mean there.

I forgot to detail my hidden agenda here -- calling the job API remotely like a true REST API.  In this case, the user should be able to accomplish as much as possible without "touching" specific filesystem paths that the server can access.

Imagine, for example, Psi/J calling a remote Psi/J as a backend.  In that case, we can assume HPC sites implement their own authentication layers on top of that REST access - so layer 1 is taken care of.

> > File contents would be preferable. IMHO, at present job specs are likely to be used in practice as "executable=/bin/bash", "args=-c,'contents of script here'".
>
> The main purpose of PSI/J is to provide an abstraction layer to job execution systems of all kinds for higher level tools, such as workflow systems. In my experience, those overwhelmingly employ structured entities rather than free-form strings. There is also a practical reason why we try to avoid script contents in the specification, and that is the nightmare that is quoting and escaping in multiple layers of shell scripts.

Even though I am trying to build a REST-API on Psi/J (in fact 2), they both generate scripts-as-strings during execution.  Asking my layer to write the files itself increases complexity.  REST needs create/update/list/destroy functions.  However, it must track as little state as possible, since multiple independent states are a source of bugs.  Tracking all the file locations and running jobs on my own duplicates effort.  Using conventions is preferable to configuring everything - especially since every piece of information in every automated script is (or should be) redundant.

A script is more general than a file path.  The script can easily call the file path, but not the other way around.  There's no need for splicing a user script into another script - a shell script can call another one.  Technically though, all the mustache splicing should be careful about script injection.

> > More importantly, however, is that the JobSpec prescribes a particular execution sequence: [...]
> > If this fails, I want to know immediately.
> I don't think PSI/J prevents that. One can always run local jobs on the login node prior to submitting a batch job and/or after. So I think that perhaps the names pre_launch and post_launch may be a source of confusion, but "launch" here refers to the specific step of starting all the ranks of a job once its resources are allocated (aka, running mpirun/srun/ibrun etc.).
> [...] We'll still need tools to allow injecting commands after the job resources were allocated but before the job is launched on all the nodes. And it is entirely possible to run what you seek without any modifications.

This operation (commands after resources are allocated but before the launcher runs) is exactly what is solved by a script-as-a-string.  As a bonus, it can use agreed-upon variables - say `$mpirun` or `$launch` to run multiple steps within the job, interspersed with more scripts, and a post-launch script. It is inconvenient to force more structure on job steps.

> > replace executable and arguments with a templated script (of any sort, it can specify its own #!/usr/bin/env ... header).
> Also see above, but this would imply less structure without much added benefit since one can always generate a script of any form outside of PSI/J and then use it as an executable in the JobSpec.

Preventing duplication of effort while allowing more uses is the benefit.  If I generate an executable script, I won't need pre_launch or post_launch or launcher commands. In fact, I can't use the launcher at all.

> > run the executable directly in the job, since the parallel "launcher" can be a template parameter like "{{mpirun}}", which expands to the appropriate "srun -n5 -c7", etc.
> While this is a possibility, the way that srun is invoked (i.e., whether directly in the job script or through another script) is largely a matter of the implementation. The reason for wrapper scripts around srun/mpirun/etc in psij-python is mostly because it simplifies the implementation and aids in debugging (the job invocation, launcher and all, is a one-liner that can be invoked manually if troubleshooting is needed).

> > The last point, exposing the job templating mechanism to the user, is critical because it prevents messy work-arounds. It also nicely supports multi-step jobs.
> 
> Perhaps I'm not understanding this well, but I don't quite see what the benefit is here or why the templating cannot be done outside of PSI/J if needed.

I'd consider doing these operations outside of Psi/J a messy workaround. Tweaking the operation spec a bit can lead to less work needed by users.

> I think there are some great scenarios here, and it may be useful to explore them further and at least add some examples of one could tackle them with PSI/J.

My opinion is that API layers 1 and 2 may not need much more work beyond what's being asked here.  Making the interface more remote-friendly, combined with a listening function like [fastapi](https://github.com/tiangolo/fastapi) or [actor-api](https://code.ornl.gov/99R/actor_api), may be all that's needed to implement layer 1.  Note also that a job-script allowed to call the launcher at will solves the "multiple job steps" (layer 2 case).

**Comment by hategan** [comment]
[...]
> > I am not entirely sure what you mean there.
> 
> I forgot to detail my hidden agenda here -- calling the job API remotely like a true REST API. In this case, the user should be able to accomplish as much as possible without "touching" specific filesystem paths that the server can access.
> 
> Imagine, for example, Psi/J calling a remote Psi/J as a backend. In that case, we can assume HPC sites implement their own authentication layers on top of that REST access - so layer 1 is taken care of.

That is pretty much what many users have been asking for and what we had planned from the start, so I think we're on the same page there.

> [...]
> 
> Even though I am trying to build a REST-API on Psi/J (in fact 2), they both generate scripts-as-strings during execution. Asking my layer to write the files itself increases complexity.

Perhaps. However, injecting code in psij scripts that run remotely can lead to subtle errors that are a nightmare to debug. It is one of the main reasons for which we separate system scripts from user scripts. Furthermore, it is really not the purpose of the PSI/J API to act as a templating engine for job scripts (even though some executor implementations do that internally).

[...] 
> 
> My opinion is that API layers 1 and 2 may not need much more work beyond what's being asked here. Making the interface more remote-friendly, combined with a listening function like [fastapi](https://github.com/tiangolo/fastapi) or [actor-api](https://code.ornl.gov/99R/actor_api), may be all that's needed to implement layer 1. Note also that a job-script allowed to call the launcher at will solves the "multiple job steps" (layer 2 case).

I'm not entirely sure if we're talking about the same "layer 2", but the "pilot job" layer 2 that the document refers to is a bit different in that it allows one to dynamically submit sub-jobs *while* resources are allocated. In other words, you don't know what the sub-jobs are until after the pilot job script is written.

**Comment by frobnitzem** [comment]
> > Even though I am trying to build a REST-API on Psi/J (in fact 2), they both generate scripts-as-strings during execution. Asking my layer to write the files itself increases complexity.
>
> Perhaps. However, injecting code in psij scripts that run remotely can lead to subtle errors that are a nightmare to debug. It is one of the main reasons for which we separate system scripts from user scripts. Furthermore, it is really not the purpose of the PSI/J API to act as a templating engine for job scripts (even though some executor implementations do that internally).

There's no essential difference between "a script that runs on the remote system" and "a file that exists on the remote system".  However, for the former, 1 extra API call (and 1 extra file location) must be managed by the caller.  There's no templating required there, just file management. 

> > My opinion is that API layers 1 and 2 may not need much more work beyond what's being asked here. Making the interface more remote-friendly, combined with a listening function like [fastapi](https://github.com/tiangolo/fastapi) or [actor-api](https://code.ornl.gov/99R/actor_api), may be all that's needed to implement layer 1. Note also that a job-script allowed to call the launcher at will solves the "multiple job steps" (layer 2 case).
>
> I'm not entirely sure if we're talking about the same "layer 2", but the "pilot job" layer 2 that the document refers to is a bit different in that it allows one to dynamically submit sub-jobs while resources are allocated. In other words, you don't know what the sub-jobs are until after the pilot job script is written.

Dynamically or not, submitting sub-jobs requires calling the launcher on demand.

**Comment by hategan** [comment]
[...]
> > Perhaps. However, injecting code in psij scripts that run remotely can lead to subtle errors that are a nightmare to debug. It is one of the main reasons for which we separate system scripts from user scripts. Furthermore, it is really not the purpose of the PSI/J API to act as a templating engine for job scripts (even though some executor implementations do that internally).
> 
> There's no essential difference between "a script that runs on the remote system" and "a file that exists on the remote system". However, for the former, 1 extra API call (and 1 extra file location) must be managed by the caller. There's no templating required there, just file management.

Let me maybe try to be more specific:

```bash
pre_launch() {
  if ] syntax error
}

pre_launch
echo "Did it work? $?"
```

Behaves very differently from

```bash
source bad_script.sh

echo "Did it work? $?"
```

That said, there is

```bash
pre_launch() {
    source <(cat <<EOF
if ] syntax error
EOF
    )
...
```

Even so, debugging issues with some `pre_launch.sh` amounts to running `source pre_launch.sh` at a prompt. It gets a bit more complex when trying to do the same with some here document in a generated submit script.

Don't get me wrong. I very much like the convenience of being able to say `spec.pre_launch = "module load xyz"` but it's not clear to me that the convenience is sufficient to offset the downsides.

> 
> > > My opinion is that API layers 1 and 2 may not need much more work beyond what's being asked here. Making the interface more remote-friendly, combined with a listening function like [fastapi](https://github.com/tiangolo/fastapi) or [actor-api](https://code.ornl.gov/99R/actor_api), may be all that's needed to implement layer 1. Note also that a job-script allowed to call the launcher at will solves the "multiple job steps" (layer 2 case).
> > 
> > 
> > I'm not entirely sure if we're talking about the same "layer 2", but the "pilot job" layer 2 that the document refers to is a bit different in that it allows one to dynamically submit sub-jobs while resources are allocated. In other words, you don't know what the sub-jobs are until after the pilot job script is written.
> 
> Dynamically or not, submitting sub-jobs requires calling the launcher on demand.

If you want to slice an allocation in order to run mpi jobs on a subset of resources, yes, although it is not the only pilot job scenario. However, I don't think that this is something that is typically exposed to users in such systems or whether we'd want to expose this to users in a possible PSI/J layer 2 implementation. The way I'd envision a layer2 implementation supporting MPI jobs is that you'd have a job with some resource requirements and the system would figure out automatically what resources are available in its existing allocations (or request a new allocation) and automatically build the relevant hostlist and invoke the launcher. I think ultimately the goal is to expose as little as possible of the internals of job launching if we want to abstract over both existing systems and pilot job systems. From that perspective, an API should be oblivious, save for configuration options, to whether the jobs are run using a scheduler directly or through a pilot job system.

**Comment by hategan** [comment]
I've opened #179 because this has been bothering me and others for a while. While there may not be a clear optimal solution at this point, it may be good to keep #179 as a reminder that there is a possibility to do better and that our collective understanding may change.

**Comment by frobnitzem** [comment]
I created an implementation for my idea and called id [psik](https://github.com/frobnitzem/psik#how-it-works).  It writes all the script strings to separate files.  The files that psi\_k generates only source or call those user files, rather than inlining them.
