### ISSUE TITLE
add examples

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#18]
add examples of how one would use this API (and please, if you have any "how do you do x?", please add here)
  - [x] Submit X jobs and wait for them to complete in order of submission with the waitFor function 
  - [x] Submit X jobs but ensure only Y job are queued/running at a time (rolling window implemented with the jobStatusCallback) 
  - [ ] Submit a job, wait for it to be queued, then cancel it, then wait for it to complete/be killed.
  - [x] Submit a malformed or unsatisfiable job, then check for the error and print it out 
  - [x] Construct a job that uses all the various "knobs" of the resource and job specifications (with some verbose comments thrown in)

No longer applicable:
- [x] do the same but use the ListException from the submit call to do the same (this is related to bulk submission, which was removed)

**Comment by hategan** [comment]
(Note: made the initial comment into a checklist)

**Comment by hategan** [comment]
A few more, from #52:

- [ ] P total processes where each process gets C cpus and G gpus
- [ ] N exclusive nodes, each with P processes
