### ISSUE TITLE
JobExecutor constructor missing

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#23]
I suggest to add a constructor which takes a backend URL as single argument, to identify the backend to connect to for job management.  The JobExecutor has a method `getName()` - I would suggest to change that to `getUrl()` to obtain that URL (or render that as an attribute on the object really):

```py
je = JobExecutor('slurm://localhost')
assert je.url == 'slurm://localhost'
```

**Comment by hategan** [comment]
I do not understand the purpose of the URL, since there is only localhost in Layer 0.

I also do not understand your code above. JobExecutor is meant as an abstract base class which cannot be instantiated directly. It would have subclasses, such as SlurmJobExecutor. Getting a specific instance of an executor would be done through a factory and the name would be relevant there:

```python
je = JobExecutorFactory.getExecutor('slurm')
assert je.name == 'slurm'
```

In Layer 1, for remote execution, I would also assume that we would use a single instance of a remote executor (of a certain type) to route jobs to different machines, so the precise location would not be tied to the executor instance, but to the job that is being submitted.

**Comment by andre-merzky** [comment]
> I do not understand the purpose of the URL, since there is only localhost in Layer 0.

An URL does not imply remote.  We can use some other format of endpoint specifier, like an unqualified string - but I assume *some* form of an endpoint specifier would be needed to let the implementation know where the backend is running (locally) it needs to connect to, and what type of backend it is.

> ... JobExecutor is meant as an abstract base class
> ... Getting a specific instance of an executor would be done through a factory

Hmm, I can see that this was clear in your mental image of the API, but I did not infer that from the text.  Why would a factory be different from a constructor?  That is really just an implementation detail again, isn't it?  A factory can be wrapped into an Constructor via delegation; a constructor can be called via a factory wrapper.  I can see that factories are probably the way to go in Java, but are not as frequently used in other languages.  Well, anyway, matter of taste, fine either way :-)

Either way though, one would need some argument which specifies not only backend type, but also the how to connect to it: be it a local port, or a socket in the file system, or whatever.  For backends like Slurm which run in system space, that knowledge may be implicitly available (a `qstat` command will connect to slurm w/o additional info), but a user space Flux instance will need the Flux-URL to connect to it's socket, a user space RCT component needs a ZMQ port to talk to, Fireworks needs a mongodb location (with access auth), etc - those endpoints are not obvious and not unique.

**Comment by hategan** [comment]
I think the point of Layer 0 is that the location of the backend is implicit.

I think we usually specify base classes in APIs when there's multiple possible implementations. That's what the doc does for `JobExecutor`. We could say that `JobExecutor` is a dummy that, in its constructor, uses a factory (and you need a factory to go from string to an instance) to create an internal instance of a subclass of `JobExecutor` and then delegate all its calls to that instance. But it seems very contrived to me. 

Your final paragraph makes multiple assumptions that, I think, may be worth reconsidering. They are, as far as I can tell:
- that there is an explicit "connection"
- that such a connection is persistent through the duration of the lifecycle of the instance of the `JobExecutor`
- that a given `JobExecutor` instance can submit jobs through one and only one connection.

While this might hold for, say, Flux, I don't think it's more like the exception than the rule. For remote execution, I would assume that, for example, we have one SSH executor instance which can route jobs to any SSH server that the use has access to by specifying the connection details either as part of additional arguments to submit() or by adding a *serviceToUse* or *remoteLocation* or *endpoint* property for the job.

**Comment by andre-merzky** [comment]
> I think we usually specify base classes in APIs when there's multiple possible implementations.

I think that is a misconception.  An API can be well defined using classes and constructors and can still have multiple implementations.  You use an abstract base class when you expect that base class to be inherited and specialized.  We can well define an API with normal classes, and implementations may choose to use abstract base classes in their code to enforce the API with different backend bindings (which then inherit that ABC).  MPI, ZMQ, HDF5, SAGA, DRMAA, RPC... - there are many API specifications around which do not use ABC (and apart from CORBA, I cannot quickly think of any which do use them).

This may be a Java thing though:  I am not a Java guy, but IIRC, Java usually defines interfaces as ABCs, right?  

> We could say that JobExecutor is a dummy ...that... delegate all its calls to that instance. But it seems very contrived to me.

This is the adaptor pattern - delegations works in any language I know, and has very low overhead (which is usually optimized away in compiled languages).  

> Your final paragraph makes multiple assumptions that, I think, may be worth reconsidering. They are, as far as I can tell:

Hmm, I can see that I gave that impression - that was not my intent.  I consider the use of `qsub` and `qstat` a valid implementation, and no single connection is needed, they can run concurrently, etc.  So I agree that these assumptions do not hold.

Ack on the '0.5' reasoning - that is what that URL parameter tries to address.

**Comment by hategan** [comment]
> > I think we usually specify base classes in APIs when there's multiple possible implementations.
> 
> I think that is a misconception. An API can be well defined using classes and constructors and can still have multiple implementations. You use an abstract base class when you expect that base class to be inherited and specialized. We can well define an API with normal classes, and implementations may choose to use abstract base classes in their code to enforce the API with different backend bindings (which then inherit that ABC). MPI, ZMQ, HDF5, SAGA, DRMAA, RPC... - there are many API specifications around which do not use ABC (and apart from CORBA, I cannot quickly think of any which do use them).

I'm using ABC in the sense of "an implementation must have these methods". It is true that there are multiple ways in which that can be done, but, while we're in the realm of OOP, I think inheritance is a rather basic assumption.

> 
> This may be a Java thing though: I am not a Java guy, but IIRC, Java usually defines interfaces as ABCs, right?
> 
> > We could say that JobExecutor is a dummy ...that... delegate all its calls to that instance. But it seems very contrived to me.
> 
> This is the adaptor pattern - delegations works in any language I know, and has very low overhead (which is usually optimized away in compiled languages).

I don't think that the adaptor pattern implies delegation. The adaptor pattern is used when a non-trivial adaptation of one API to another is needed. Delegation is the evaluation of one API in a context of an object different than the one on which the methods are called, but the methods are the same and there is no translation of the parameters.

What you are suggesting is using delegation to invoke methods in an adaptor class by calling methods in a unified front-end class. So we would have both the adaptor class AND the delegation step. It's not that it's slow, but that it's unnecessary if you can get direct instances of the adaptor classes.

But perhaps it's better to talk in code:

```java
// With factories:

e = JobExecutorFactory.getInstance("slurm"); // assert(e.getClass() == SlurmJobExecutor.class);
e.submit(job);

// With delegating JobExecutor
e = new JobExecutor("slurm"); // does e.delegate= JobExecutorFactory.getInstance("slurm");
e.submit(job); // does e.delegate.submit(job);
```

So with the latter we created a facade which doesn't really simplify anything. I'd call this unnecessary complexity: nothing is gained, more code is written. I guess, ultimately, if you are delegating ALL methods, something is probably wrong in the design.

Of course, this makes the fundamental assumption that there is no voodoo that would be invalid in any decent strongly typed language, but which you can do in python:

```python
import pathlib

p = pathlib.Path('/')
print(type(p)) # <class 'pathlib.PosixPath'>
```

But that's really just using the constructor as a factory without doing delegation. Still a distasteful consequence of Python's loose morals if you ask me.

> [...]

**Comment by andre-merzky** [comment]
That is all as it may - I think I got too much into detail so my point got lost, apologies.  My point the same as in the other discussion strands I think: factory my be great, and adaptors may be great -- but I don't think a language independent API spec should put either approach as normative, that is an implementation choice and thus is twice removed from this document (1: language binding, 2: implementation).  This document should not judge about the coding morals of a developer who chooses the `pathlib` approach in it's Python implementation....

**Comment by andre-merzky** [comment]
On a more technical note:  ABS implies early binding of implementation to API.  For a job API that is not much of a problem, but for a data API it actually is.  Consider the following code:

```py
file = sagav2.createFileObject('file://localhost/bin/date')
assert type(file) == 'sagav2.backend.local_file.File'
file.copy(tgt='scp://some.host/tmp/my_date')
file.copy(tgt='rsync://some.host/tmp/my_date')
```

With a factory pattern, the `file` instance is represented by an implementation which can speak to localhost - but which cannot run the copy commands.  That would require it to speak to different backends, violating backend separation.  A plain constructor can well do that:

```py
file = sagav2.File('file://localhost/bin/date')
file.copy(tgt='scp://some.host/tmp/my_date')
file.copy(tgt='rsync://some.host/tmp/my_date')
```

Nothing in this code says that both copies need to be implemented in the same adaptor (or backend binding in general), via delegation:
```py
class File(...):
    def __init__(self, url):
        self._url = url
    def copy(self, tgt):
        adaptor = magic_adaptor_select(self._url, tgt)
        adaptor.file_copy(self._url, tgt)
```
But again, that discussion has no place in this document, but might be relevant to the language binding.

**Comment by hategan** [comment]
> That is all as it may - I think I got too much into detail so my point got lost, apologies. My point the same as in the other discussion strands I think: factory my be great, and adaptors may be great -- but I don't think a language independent API spec should put either approach as normative, that is an implementation choice and thus is twice removed from this document (1: language binding, 2: implementation).

Hence the lack of a constructor or a mention of a factory in the document. I wanted to add a non-normative note to that extent, and it seems wise to do so.

> This document should not judge about the coding morals of a developer who chooses the `pathlib` approach in it's Python implementation....

The pathlib approach is a bit of a gray area specific to python. I don't think the document should say anything about that.

I also, as a general statement, do not think the document should encourage well known anti-patterns.

**Comment by andre-merzky** [comment]
> Hence the lack of a constructor or a mention of a factory in the document. I wanted to add a non-normative note to that extent, and it seems wise to do so. 

Right, that makes sense I guess - but what to do about parameters needed for initialization?

**Comment by hategan** [comment]
> On a more technical note: ABS implies early binding of implementation to API. For a job API that is not much of a problem, but for a data API it actually is. Consider the following code:
> 
> ```python
> file = sagav2.createFileObject('file://localhost/bin/date')
> assert type(file) == 'sagav2.backend.local_file.File'
> file.copy(tgt='scp://some.host/tmp/my_date')
> file.copy(tgt='rsync://some.host/tmp/my_date')
> ```
> 
> With a factory pattern, the `file` instance is represented by an implementation which can speak to localhost - but which cannot run the copy commands. That would require it to speak to different backends, violating backend separation. A plain constructor can well do that:
> 
> ```python
> file = sagav2.File('file://localhost/bin/date')
> file.copy(tgt='scp://some.host/tmp/my_date')
> file.copy(tgt='rsync://some.host/tmp/my_date')
> ```
> 
> Nothing in this code says that both copies need to be implemented in the same adaptor (or backend binding in general), via delegation:
> 
> ```python
> class File(...):
>     def __init__(self, url):
>         self._url = url
>     def copy(self, tgt):
>         adaptor = magic_adaptor_select(self._url, tgt)
>         adaptor.file_copy(self._url, tgt)
> ```
> 
> But again, that discussion has no place in this document, but might be relevant to the language binding.

I don't think the methods implemented have anything to do with how one grabs an instance of a particular class. In your second case, you still need something to be able to communicate data between two different filesystems. In other words, there is no magic_adaptor. It has to be implemented and, it has to know how to talk to both source and target. Of course, the more reasonable way to implement this would be to have each FS class be able to communicate in a common language, such as having the ability to open input/output streams from/to files, which can then be piped into one another, even if the filesystems are different and without violating the idea that each implementing class only knows about one type of FS.

**Comment by hategan** [comment]
> > Hence the lack of a constructor or a mention of a factory in the document. I wanted to add a non-normative note to that extent, and it seems wise to do so.
> 
> Right, that makes sense I guess - but what to do about parameters needed for initialization?

It wasn't in the plan for layer 0 to have more than implicit things. 

There's two possibilities we have: 
1. the adapters are stateless and any configuration sits with the job or a request (i.e., like, for example, one HTTP adapter instance could be used to GET pages from multiple servers and the "configuration" is in the request)
2. the adapters are stateful, have a fixed configuration, and represent one connection to a backend

I don't feel too strongly about it, but:
- I think stateless and concurrency are a good match
  - it's really not that stateful if the state only changes during initialization, so I'm not really sure the concurrency point matters much
- it feels like (2) is making assumptions about how an implementation handles its communication, which maybe we don't want

**Comment by andre-merzky** [comment]
> In other words, there is no magic_adaptor. It has to be implemented and, it has to know how to talk to both source and target.

Right - but you could implement one adaptor to copy `local -> ssh -> remote`, and another adaptor for `local -> rsync -> remote`, both operating on the same instance.  So, no `magic_adaptor`, but a `magic_adaptor_select` which finds out what adaptor to use, based on the urls involved.  You would _not_ need a single adaptor which understands both protocols.  

When using a factory which returns a specialized `File` object implementation, like a `LocalFile`, `SSHFile`, or `RsyncFile`, one generally binds that object against a single adaptor, which would then need a `LocalSSHRSyncFile` implementation to understand both protocols in order to run the code above.

FWIW, that is what we do that late adaptor binding in our SAGA implementation, at least in some places (it is kinda useless for job adaptors).

> the more reasonable way to implement this ...

Yeah, I also like standards :-D

**Comment by hategan** [comment]
> > the more reasonable way to implement this ...
> 
> Yeah, I also like standards :-D

Yeah. And there's a fine line between micromanagement and saying just enough to steer the implementations in the right direction.

**Comment by andre-merzky** [comment]
> It wasn't in the plan for layer 0 to have more than implicit things.

Hmm, I would expect a spec to be precise and explicit enough that it does not leave room for speculation ;-)


> *  it feels like (2) is making assumptions about how an implementation handles its communication, which maybe we don't want

Yeah, I would really like to stay away from making assumptions about an implementation (as you probably figured out by my stubborn insistence on that :-P), so appreciate that comment.

**Comment by hategan** [comment]
> > It wasn't in the plan for layer 0 to have more than implicit things.
> 
> Hmm, I would expect a spec to be precise and explicit enough that it does not leave room for speculation ;-)

My bad. I said "local LRMs". I can add a note that explicitly states that location is implicit.

This, of course, isn't sufficient. I can envision the possibility of having a configuration for the adapter, even when the location is implicit. I can't think of anything concrete right now, but I have a suspicion we'll get there. So it may be that we'll have to provide some means for configuring an adapter. Or, it may also be that we'll leave that detail to whoever implements things.

**Comment by andre-merzky** [comment]
This stalled for a while by now, and also stalls #26.  I am not sure where the above discussion left us, really.  Should I interpret your last comment as `some initialization parameters may be justified` and thus as `a constructor would be justified`?

**Comment by andre-merzky** [comment]
@hategan , @SteVwonder : I propose to take this out of the alpha release. We did agree (I think) that the constructor specification and parameterization is a language binding issue and thus does not need to be added into the spec at this point.
