### ISSUE TITLE
API Compatibility Across Implementations?

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#27]
My assumption is this:
  - the document defines, in a language independent way, a set of classes and methods (the 'API') which abstracts job specification,  submission and management towards an execution backend.
  - we expect different language bindings to emerge for that API
  - we expect different implementations to emerge for those language bindings
  - the document is informed by existing bindings and implementations, but is not normative toward the language bindings nor towards the implementations,

I am not sure if my assumptions are valid - please discuss.  Thank you.

**Comment by hategan** [comment]
I agree. I might have made a point, however, on defining degree of "normativity" in a slightly different way: should we expect reasonable source-code compatibility between different implementations?

I would say yes: that a user should have to make minimal changes/refactoring if switching between implementations, but that we do not mandate that no changes whatsoever be necessary.

For example, I think if we specify properties for a class, they should be translated into getters and setters in Java, properties in Python, but not naked dictionaries in either. That is, I would not like a client to have to change `job.executable = '/bin/sleep'` into `job['executable'] = '/bin/sleep'` when switching implementations (even if `job.executable = '/bin/sleep'` is internally implemented as `self._dict['executable'] = value`. In Java, this makes even more sense because the setters/getters allow more fine-grained type checking to occur, so, while it doesn't matter much in python, there is a material difference in Java (and strongly typed languages).

That said, it's totally not the end of the world if somebody goes ahead and implements things with dictionaries. We will have no official certification mechanism, no means to enforce any of these rules, and, to a large extent, we shouldn't want to: somebody may actually make a better version of this API (although, perhaps, that won't be by implementing everything with dictionaries). The single biggest value of this API at Layer 0 would be to have re-usable implementations of programmatic interfaces to LRMs that have some minimal standards of decency.

**Comment by andre-merzky** [comment]
> should we expect reasonable source-code compatibility between different implementations?

Well, that is why we have an API, right?  In Python I would assume this:

```py
import flux.sagav2 as saga
je = saga.JobExecutor()
job = saga.Job()
je.submit(job)
...

import slurm.sagav2 as saga
je = saga.JobExecutor()
job = saga.Job()
je.submit(job)
...

I would assume this to be valid.  If the API is well defined, we can switch implementations.  Same for C (include different headers, link different library - but the application code remains unchanged) or any other language.

_*How*_ the module / library is implemented is of no concern to me: the module can phone small imps which tells tiny daemons to perform physical tasks for me for all I care... - as long as at the end the call provides the semantics as defined in our specification.

> That is, I would not like a client to have to change job.executable = '/bin/sleep' into job['executable'] = '/bin/sleep' when switching implementations

Oh no, most certainly not!  At least not when we talk about the same language.  But our spec does not assume a language really: where an attribute may be good in Python, a property might be better in C++ and setter / getter might be better in Java.  I am not sure we need to define the actual mechanisms just yet.  

Maybe we should also write down some language binding - maybe Python as that seems a low hanging fruit?  That might clear some things up, too.  But I certainly think that this would be a different document?

**Comment by SteVwonder** [comment]
> should we expect reasonable source-code compatibility between different implementations?

>> I would say yes: that a user should have to make minimal changes/refactoring if switching between implementations, but that we do not mandate that no changes whatsoever be necessary.

>> If the API is well defined, we can switch implementations. Same for C (include different headers, link different library - but the application code remains unchanged) or any other language.

I agree that we should strive for source-code compatibility between implementations.  I think the main incompatibility will be the custom attributes, the specific error messages, and implementation-specific metadata (e.g., Flux handles). But if you stick to the core functionality (@andre-merzky 's example above is a good one), I think that should "just work" regardless of implementation.

> Maybe we should also write down some language binding - maybe Python as that seems a low hanging fruit? That might clear some things up, too. But I certainly think that this would be a different document?

Agreed.  Maybe this should be the next step before we dive into making an initial implementation?  Maybe create a small python file with function stubs and docstrings?  If we do that, we could then run Sphinx on it and auto-generate nice documentation for it.

**Comment by hategan** [comment]
> > should we expect reasonable source-code compatibility between different implementations?
> 
> Well, that is why we have an API, right? In Python I would assume this:
> 
> ```python
> import flux.sagav2 as saga
> je = saga.JobExecutor()
> job = saga.Job()
> je.submit(job)
> ...
> 
> import slurm.sagav2 as saga
> je = saga.JobExecutor()
> job = saga.Job()
> je.submit(job)
> ...
> ```

By "implementation" I meant entire implementations. E.g., teams A and B reading the spec and implementing it from scratch. How easy do we want to make it to switch from one to the other.

**Comment by andre-merzky** [comment]
> > > should we expect reasonable source-code compatibility between different implementations?
> > 
> > 
> > Well, that is why we have an API, right? In Python I would assume this:
> > ```python
> > import flux.sagav2 as saga
> > je = saga.JobExecutor()
> > job = saga.Job()
> > je.submit(job)
> > ...
> > 
> > import slurm.sagav2 as saga
> > je = saga.JobExecutor()
> > job = saga.Job()
> > je.submit(job)
> > ...
> > ```
> 
> By "implementation" I meant entire implementations. E.g., teams A and B reading the spec and implementing it from scratch. How easy do we want to make it to switch from one to the other.

That is what the example shows, isn't it?  What am I missing?

**Comment by andre-merzky** [comment]
Language  bindings:

> Agreed. Maybe this should be the next step before we dive into making an initial implementation? Maybe create a small python file with function stubs and docstrings? If we do that, we could then run Sphinx on it and auto-generate nice documentation for it.

Yes,.

**Comment by hategan** [comment]
> > > > should we expect reasonable source-code compatibility between different implementations?
> > > 
> > > 
> > > Well, that is why we have an API, right? In Python I would assume this:
> > > ```python
> > > import flux.sagav2 as saga
> > > je = saga.JobExecutor()
> > > job = saga.Job()
> > > je.submit(job)
> > > ...
> > > 
> > > import slurm.sagav2 as saga
> > > je = saga.JobExecutor()
> > > job = saga.Job()
> > > je.submit(job)
> > > ...
> > > ```
> > 
> > 
> > By "implementation" I meant entire implementations. E.g., teams A and B reading the spec and implementing it from scratch. How easy do we want to make it to switch from one to the other.
> 
> That is what the example shows, isn't it? What am I missing?

I missed the different Job classes.

Again, one could have job.executable for the first and job.['executable'] for the second.

**Comment by andre-merzky** [comment]
> Again, one could have job.executable for the first and job.['executable'] for the second.

Not really, the language binding would define which one has to be valid.  Well, it could define that both work, but then both would work in both implementations.

**Comment by hategan** [comment]
> > Again, one could have job.executable for the first and job.['executable'] for the second.
> 
> Not really, the language binding would define which one has to be valid. Well, it could define that both work, but then both would work in both implementations.

I feel like we're making some assumptions that aren't quite the same here.

Let's say we have Vendor A (e.g., us), implementing flux.sagav2. And then we have Vendor B (eg., somebody from The Slurm Company), implementing slurm.sagav2. They did not talk to each other when they wrote the implementations. The only thing they had was "the document". We did not specify, in "the document", whether python implementations should use properties or dictionaries or even getters and setters. The vendors are free to pick.

Does this fit with your scenario?

**Comment by andre-merzky** [comment]
> We did not specify, in "the document", whether python implementations should use properties or dictionaries or even getters and setters. The vendors are free to pick.

Oh right, exactly!  And that is why I definitely would expect that we need to write a language binding spec for the API!  That can be extremely small, just stating how the spec (the document we do right now) looks like in the target language: types, exceptions / error code, and the like.  That binding would be silent about semantics, as that is well defined in the API spec.

I am really sorry that I expressed that so poorly - I always mentioned 'language binding', but should have made clear that I mean the _specification_ of such a binding, not the _implementation_ of it...  

So, I would assume that a vendor uses *two* documents: this one, where we define classes, methods, constants, and the semantics of it all, and the (small) language binding spec, which defines how that API has to look in, say, Python.

**Comment by hategan** [comment]
> > We did not specify, in "the document", whether python implementations should use properties or dictionaries or even getters and setters. The vendors are free to pick.
> 
> Oh right, exactly! And that is why I definitely would expect that we need to write a language binding spec for the API! That can be extremely small, just stating how the spec (the document we do right now) looks like in the target language: types, exceptions / error code, and the like. That binding would be silent about semantics, as that is well defined in the API spec.
> 
> I am really sorry that I expressed that so poorly - I always mentioned 'language binding', but should have made clear that I mean the _specification_ of such a binding, not the _implementation_ of it...
> 
> So, I would assume that a vendor uses _two_ documents: this one, where we define classes, methods, constants, and the semantics of it all, and the (small) language binding spec, which defines how that API has to look in, say, Python.

No worries.

There's an "Implementation notes" section for that. Although, again, we may want to be clear what our standard is for defining how much bindings should be similar.

And once again, and sorry for repeating this, I consider this a master document; an in-depth analysis. Once we reach reasonable agreement on it, we can extract sub-documents relevant to a particular context.

**Comment by andre-merzky** [comment]
> There's an "Implementation notes" section for that. Although, again, we may want to be clear what our standard is for defining how much bindings should be similar.

There should not be an option of different implementors defining their own language bindings. Otherwise, what is the point of specifying an API?

> And once again, and sorry for repeating this, I consider this a master document; an in-depth analysis. Once we reach reasonable agreement on it, we can extract sub-documents relevant to a particular context.

Maybe we should do that sooner, and maybe agreement is then actually simpler :-)

**Comment by SteVwonder** [comment]
Let's move the conversation about API compatibility from #26 over to here.  Copying over some relevant bits (attribution for the ideas in the quotes goes to @hategan and @andre-merzky)

>> So even though JobExecutor, as an ABC, may have a constructor, this does not imply that it needs to be specified by JPSI.

> I expect of an portable API that all public method are specified. Otherwise portability goes out of the window in a heartbeat. If one implementation implements je.submit_special() and another implements je.submit_extra(), then what's the purpose of the spec? A user needs to change code when switching implementation, so the spec becomes kind of useless. Or am I missing the point you are trying to make?

---

>> I think we still haven't decided the extend of source-level compatibility we want to have

> See here: I expect that at least a user can switch between implementations by importing or including/relinking a different implementation, w/o other code changes. I personally don't care about binary compatibility, or compatibility on the adaptor layer (if one exists in the implementation). That's the minimal portability definition which seems to make sense.

---

> > > > It is also fine to not have complete source-level compatibility as far as I'm concerned.
> > > 
> > > Uhm... what compatibility is then left?
> > 
> > Having to make a few cosmetic edits here and there is much better than having to re-design my whole program because, say, the API I'm switching to is synchronous and the old one was async.
> > 
> > Ideally, I'd like to be able to say that we came with a spec that somehow makes all implementations be switchable by changing some import statements. But you should note that, should we achieve that with the spec, you and I, writing two different implementations of the spec, would come up with two things that can be swapped by changing import statement only. Do you think that's realistic?
> 
> If I would not have that ability, then the spec is not useful to our use case.  The whole purpose of > that API is, for us, to avoid code like
> ```
> if use slurm,v2: ...
> if use slurm,v3: ...
> elif use pbs: ...
> elif: use flux
> ...
> ```
> 
> I MUST be able to use the same code against different backends.

---

> > I think I was explicit, really:
> >
> > * I MUST be able to talk to two Flux instances to make this API in any way useful to RCT.
>
> Perfect. We can talk about initializing that thing that talks to Flux to communicate to it/them the correct instance.
>
> > * I MUST be able to switch Slurm/PBS without code changes to make this useful to RCT.
>
> Also perfect. A URL passed to a frontend JobExecutor is not the only way to do this and we should not mandate that.
>
> > * I MUST be able to talk to Slurm and Flux from within the same code base, in the same process, at the same time.
>
> Agreed. Inheritance is the mechanism invented to address just that problem and would be the most obvious way to structure the
> API, but I think you disagree with that, so, if we want consensus, we want to not mandate it one way or another.
>
> > * I SHOULD be able to implement this API w/o ABC to make it a useful spec for RCT.
>
> Excellent. I should also be able to implement this API by considering JobExecutor to be an ABC.

**Comment by SteVwonder** [comment]
From #73:

>>> wait() is a final method in Java, so, in Java it can't be wait().
>> I understand then that the Java binding will have waitFor, but that should not affect all other languages, right?
> It was my impression that we're aiming for a spec that doesn't leave that much room for interpretation.

Yes, my impression is that within a programming language we wanted little room for interpretation to maximize compatibility across implementation in the same language (e.g., python). I would be ok with allowing for some variation across languages (e.g., you shouldn't use `id` in python since it is top-level function, but maybe that is ok for java, and you shouldn't/can't use `wait` in Java but it is perfectly fine in python).  This would allow us to make the API more idiomatic for each language and leverage language-specific feature (e.g., iterators in Python).  If we do that, for each language we should document the bindings such that each implementation for that language is the same.

**Comment by andre-merzky** [comment]
Added the January milestone - we should have basic clarity by then on what level of interoperability we are targeting.

**Comment by SteVwonder** [comment]
(Hopefully representative) summary from our meeting today:

With J/PSI, we expect there to be both "frameworks" and "adaptors".  A "framework" is an implementation that provides the things that do not get re-written across implementations (e.g., exceptions and certain core classes).  An "adaptor" is an implementation for a connection into a specific RM that is written against a particular "framework".

As an example, our exaworks group may develop an "exaworks framework" that includes adaptors for Flux and Radical Pilot.  Slurm may copy our framework into their codebase and implementor their own adaptor for Slurm.  A closed-source scheduler may write their own framework (i.e., ground-up implementation of the API).

We had consensus on the goal of striving for source-code compatibility across frameworks and binary-compatibility across adaptors within a framework.

This would enable users to write code once and have it work against multiple frameworks (when using one at a time) and also enable a single process to connect to multiple RMs using a single framework with multiple adaptors (and create a binary-compatible job instance that could be submitted to any of those adaptors).

For a language like Python, ABI compatibility is less of a concern, so even more functionality is possible with just source-code compatibility across frameworks.

**Comment by hategan** [comment]
Thanks Steven. I'll add a few notes about some deeper issues that I believe drive some of the details. They're more rhetoric than me inviting a discussion, and I'm writing this because it may explain what otherwise may seem like a peculiar angle.

- I don't expect people to flock to writing JPSI frameworks; in the golden days of the Grid and standardization, people didn't exactly flock to implementing SAGA (or Globus V3) either. Unless we implement a JPSI framework, there likely won't be a JPSI framework. That tells me to be less concerned with the perfect specification/standard as to be with having a robust and implementable API.
- If our framework, with some common connectors, ends up being scalable and robust, easy to install and use, and if it reasonably addresses typical usage scenarios, it may get used.
- if it gets used, people may have a vested interest in improving it; if, then, the framework makes it easy to adapt existing connectors or write new connectors, it may have a chance of surviving in the long run
- if all of the above, JPSI may prove successful enough to be maintained by a community and be ported to other languages and, therefore, fulfilling its goal of not being Yet Another Grid API.

So we can spend lots of time discussing source level and binary and whatnot compatibility, but I suspect we might be barking at the wrong tree. Of course, I could be wrong about any or all these things.

**Comment by andre-merzky** [comment]
I am re-opening this as the discussion came up again:

---- 
From #128 :

@SteVwonder 

> > `jex = jpsi.JobExecutor()`
>
> Not directly related to your spelling fix, but as a side question: What is a call to this constructor with no arguments supposed to > return? It isn't specified in the doc. I'm guessing just a local connector/executor?

> @andre-merzky 
> A specific implementation might pick up the connector settings out of band? For example,
> ```py
> from flux import jpsi
> jes = jpsi.JobExecutor()
> ```

> @hategan 
> But the jpsi package use there is awfully confusing. Everywhere else in the examples it is used as the jpsi package where, say, Job resides.

> [...] I'd rather we had a model in which not every connector contributor would have to re-write all the core classes.
> [...] So [the above would not work] in the scenario in which flux contributes an executor to an existing library.

> @andre-merzky 
> Just for the record (and off-topic here): there are better ways to allow implementation reuse than asking the user to import two different modules and needing to remember what module to use for what part of the API... brrr...

> @hategan 
> Oh, agreed. And I think psi.j.JobExecutor.get_instance("local"/"flux"/"rp") or psi.j.JobExecutor("local"/"flux"/"rp") both fit the bill.
