### ISSUE TITLE
Meta: PR Merge Criteria

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/job-api-spec#30]
When are PRs allowed to be merged?  Do they require 1 approval? 2?  Can someone click the merge button on their own PR?

I think every project has their own way of doing things.  We just need to pick one and stick with it.

My suggestion would be: there is at least 1 approval, no requested changes, and someone other than the submitter merges the PR (either another maintainer or we setup a bot to do automatic merging and constraint checking).

Any thoughts or alternate suggestions?

**Comment by hategan** [comment]
All good questions. I'm personally not a huge fan of bureaucracy. That said, I think an extra set of eyes can't hurt. So I agree with your suggestions. I might add:
- reviews should be timely (both reviewer and PR issuer should make a good attempt at resolving the conversation as quickly as possible)
- reviews aren't there to ensure perfection of a PR, but as a check to ensure obvious things aren't missed (this is a point of view and there are others, incompatible with it)
- sometimes a conversation is there to answer a question or just as a general comment; it may be wise to mark them as such somehow
- whoever opens a conversation should close it
- whoever closes the last conversation should merge the PR, so maybe no bot
- use draft PRs if it's not completed work
