### ISSUE TITLE
Launchers discussion/requirements

### ISSUE THREAD

**Issue by hategan** [ExaWorks/job-api-spec#51]
This issue is here to discuss what we need to add to the API to support the wealth of launchers that is out there and their peculiarities.

A good first step would be to gather use cases based on what folks have had to deal with so far.

The basic assumption of adapters is that they will write a submit script which will communicate all relevant parameters to the LRM, after which they will launch the user application in a launcher command. The launcher command may be wrapped in some miscellaneous code that aggregates exit codes and outputs if necessary.

For example:
```bash
#!/bin/bash

# submit script part
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=24
#SBATCH --time=00:30:00
#SBATCH --exclusive
#SBATCH --account=abcd

# launcher command
srun --open-mode=truncate ./myapp
```

In the above example, the launcher can be specified as a string, with provisions for expanding various jobspec properties. For example:

```
srun --open-mode=truncate ${spec.executable} ${spec.arguments}
```

Of course, we would need a slightly more complex templating engine, one where you could specify that `${spec.arguments}` is a list whose elements should be separated by spaces and, perhaps, properly quoted.

So anyway, please add comments with what you would expect in a launcher.

**Comment by andre-merzky** [comment]
I am not sure that is the right question to ask.  The `wealth of launchers [...] and their peculiarities` will (in principle) result in a near-infinite list of specificities and corner cases, but will not necessarily provide any guidance which ones we consider important enough to cover by the API.  

Just as an example, take the `map-by` family of parameters on `mpirun` (openmpi), which don't have a direct correspondence in, say, aprun.  So now we know that exists - but what does that mean for an abstracting API?

SAGA would opt for only including things which have been explicitly required by use cases.  DRMAA would cover the union of all options, and define a launcher extension point with a query interface to what extension would be acceptable by the implementation.  I find it difficult to see a middle ground - do you?

**Comment by SteVwonder** [comment]
> I find it difficult to see a middle ground - do you?

Not sure if this is a middle ground, but maybe opting for only including things that are required by the exposed J/PSI interfaces.  Then providing a "release valve", where you can insert arbitrary arguments to the launcher.  The latter bit is a total cop-out but it at least seems simpler and easier to use/implement than a full-blown query and extension interface.  If enough people are inserting `--foobaz=bar` in various forms to their launchers, then we add a `foobaz` interface to J/PSI proper?

**Comment by andre-merzky** [comment]
> PS - Maybe SAGA also provides a similar "release valve"? If so, how did that work out?

Not really: we decided very early on that we expected not to cover 20% of the use cases, and thus would not allow lower layer abstractions to leak through the API.  So, the API spec does not allow that at all.  But on an implementation level, we allow configurations, and config files are easily overwritten by users, or in a specific deployment.  So we can tweak the behaviour, but keep the tweaks out of the code which remains portable.

That approach comes with it's own problem: ever growing number of config options, need to maintain config files per resources, etc.  But ultimately it works reasonably well for us.

**Comment by andre-merzky** [comment]
> providing a "release valve", where you can insert arbitrary arguments to the launcher.

That would certainly work, and I can see how that would expand the set of use cases the API can be used for.  The drawbacks I can see:

  - valve settings can contradict settings chosen by the implementation
  - those conflicts can result in hard to interpret error messages
  - the code becomes non-portable

**Comment by hategan** [comment]
> I am not sure that is the right question to ask. The `wealth of launchers [...] and their peculiarities` will (in principle) result in a near-infinite list of specificities and corner cases, but will not necessarily provide any guidance which ones we consider important enough to cover by the API.

We need some use cases.

I do not think the API part that specifies a job will change. But we need to understand how that gets mapped to various launchers and if we are not doing something silly to hinder usage that would otherwise be easy to address. Basically, we shouldn't go blind into this venture.

**Comment by hategan** [comment]
There is a parallel, and seemingly more fruitful, discussion in #16. I am closing this issue as redundant.
