### ISSUE TITLE
Add more examples of API use

### ISSUE THREAD

**Issue by hategan** [ExaWorks/job-api-spec#52]
Some examples have been added by PR #47. However, not all requested examples in the initial TODO are added by that PR. The reasons are listed in the PR comments. This is an issue mean to track the remaining examples in the TODO item so that the PR can be merged as is for now.

**Comment by SteVwonder** [comment]
For the "exotic"/"complex" requests, I think it would be good to have a few examples that construct some "complex" ResourceSpecifications (doesn't need to be the full job). Two in particular:

- P total processes where each process gets C cpus and G gpus
- N exclusive nodes, each with P processes

It would also be good to have an example that constructs a JobAttribute, sets a value on it, and then adds that JobAttribute to a JobSpecification.

An example that changes the environment would also be a good one.

**Comment by hategan** [comment]
I'll add a couple more items here in an effort to move away from an in-document todo list. They are:

- [ ] Submit a malformed or unsatisfiable job, then check for the error and print it out
- [ ] Construct a job that uses all the various “knobs” of the resource and job specifications (with some verbose comments thrown in)

**Comment by hategan** [comment]
I am merging this issue into #18.
