### ISSUE TITLE
How will implementations and "providers" be created/managed/structured

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/job-api-spec#53]
I'm not exactly how to title this issue, but I think ultimately my question boils down to: do we expect there to be a single reference implementation with many providers (one per target RM) or many implementations (one per target RM)?

More verbosely:

- Do we expect there to be a single reference implementation with many providers (one for slurm, one for Flux, one for RP, one for LSF, one for local, etc)?
  - I think of this as all of the implementations/providers residing in a single source repo, downloadable and installable as a single package (e.g., `pip install jpsi`), and then usable as a single package (e.g., `import jpsi`).
- Do we expect each RM to have their own implementation?
  - I think of this as the implementations are scattered across multiple repos.  Maybe the Flux implementation is in the flux-framework repo importable as `import flux.jpsi as jpsi` (same for RP), the Slurm implementation is in an ExaWork repo importable as `import slurm.jpsi as jpsi` (same for LSF).
  - Each package would then have to be downloaded and installed independently (e.g., `pip install jpsi-flux`, `pip install jpsi-radicalpilot`, `pip install jpsi-slurm`.)
- Do we expect some kind of hybrid of these two?
	- Maybe the Exaworks participants that will be providing jpsi (e.g., Flux and RP) can merge it into their repos directly, the closed-source RMs can have their providers in an open-source repo (e.g., Exaworks/jpsi-lsf), and open-source RMs that aren't a part of Exaworks can have their implementations start in the Exaworks reference implementation and then maybe transition to being in their own organization/repos (although I highly doubt that transition ever takes place)?

PS - I'm using the term RM (resource manager) to basically mean anything that will implement J/PSI.

**Comment by SteVwonder** [comment]
For the single reference implementation, I think the benefit is that it makes it simple for a user to install and use the interface.  They install one package, and it "just works" for any of the supported providers.  It also makes it easier to test, since all of the providers are in the same repo, you can run them all against the same CI and ensure they stay in sync.  The downside is that the implementation is now tied to ExaWorks the entity, which won't be funded forever.  I could see how the reference implementation could quickly bit rot after Exawork funding dries up.

For the multi-implementation case, I think the benefit is that the maintenance burden is distributed across the various RMs/providers, so they are more likely to outlive Exaworks - the funded project.  The downside is that now users have to download and install multiple packages for full functionality/portability (and maybe we provide a small shim in the reference implementation to automatically import the "right" provider/implementation).

The hybrid use case described above would eliminate some of the downsides of a full multi-implementation case by allowing some RMs to natively provide J/PSI.  Meaning that users wouldn't have to download or install anything when running on a cluster managed by (for example) Flux or when using a pilot system like (for example) Radical Pilot.  They would only need to download and install packages when using a closed-source RM like LSF or a "third-party" open-source RM like Slurm.

In terms of prior art, I think (I could be totally wrong) that SAGA is an example of the single reference implementation case and DRMAA is an example of the multi-implementation case.

**Comment by hategan** [comment]
I'd expect a set of core classes and adapters as plug-ins to that core infrastructure.

Our distribution would have the core, adapters for widely-used LRMs, as well as some reference/testing local adapter.

It would also have a mechanism for easily finding and allowing the instantiation of user-supplied adapters.

For example: `pip install jpsi-core jpsi-common-adapters` would install our stuff; then one could do `pip install jpsi-cobalt-anl` to install an anl-developed adapter for Cobalt. 

I think this  matches your hybrid use case.

**Comment by andre-merzky** [comment]
> In terms of prior art, I think (I could be totally wrong) that SAGA is an example of the single reference implementation case and DRMAA is an example of the multi-implementation case.

Just for completeness: SAGA did not, at all, want to be a single implementation, and at some point in the past had 4 active implementations actually.  `radical-saga` is just the last on left standing :-)  Full ack on DRMAA though, they always targeted that case (vendor implementations).

I actually think we should not worry about that part.  I mean, suppose we decide for a single ref implementation, and somebody comes along and provides a separate implementation for RM-X.  What are we gonna do?  Whine?  Are rejoice because somebody thought our API is worthy their time to implement? :-)

An API spec should not prescribe the number of implementations.  Number, style and scope of of the implementation(s) *within the exawork project* certainly need discussion, but not as part of this document.  

I can speak for our RCT perspective: if we want to use JPSI as SAGA replacement, we (a) need it to support multiple backends, and (b) cannot wait for vendors to provide implementations.  But also, should a vendor provide an implementation, I'd rather use that than rolling our own...

**Comment by hategan** [comment]
This is mostly an implementation question.

However, the current reference implementation (psij-python) has a rather flexible mechanism that allows all kinds of things, including user-installed connectors working with system-installed psij core and vice versa.

Closing for now.
