### ISSUE TITLE
Pre, post, scripts, expansion, etc.

### ISSUE THREAD

**Issue by hategan** [ExaWorks/job-api-spec#54]
During the meeting on 11/20/20, there was an extended discussion that was started by PR #50.

It started with the motivation behind performing environment variable expansion for values in the environment dictionary of the jobspec. The use case behind that was the need to support doing the equivalent of `PATH=/some/path:${PATH}`.

This led to another question: What if the user wants to do `VAR1=value1` then `VAR2=value2/${VAR1}`. That is, reference a variable defined in the environment *earlier*. The problem is that, since the jobspec environment is stored in a dictionary, there is no clear order that would allow an implementation to know what was set *earlier*. To support that scenario, we would need to change the dictionary to a list of name/value pairs. This is all fine, but it is getting uncomfortably close to "why don't we just allow the user to specify a bunch of shell commands to be executed before the executable is launched?". That is, why not just dump any fancy processing in the API and have pre/post-execs instead. That would allow a lot of flexibility.

But then, the law of slippery sloping would dictated that maybe we should have a rather simplified API that specifies 3 scripts:
1. a pre script, running on the rank 0 node, which can contain all necessary `module load` commands, environment manipulations, etc.
2. an in-scipt, running on all ranks, which can contain the executable and all arguments
3. a post-script, also running on the rank 0 node, which can contain all necessary cleanup and aggregation

This would make the following features of the API unnecessary:
- executable/arguments (the in-script is sufficient)
- environment variable expansion in the environment dictionary
- possibly the whole environment dictionary (the users could simply set things in the pre-script)
- possibly output redirection, which could be handled by the in-script and post-scripts
- the directory; a cd command in the pre-script or in-script may suffice

Anyway, lots to think about...

**Comment by andre-merzky** [comment]
*"make the common case simple, and the special case possible"*.  In that sense I would argue that we should not dispense of executable, output redirection etc. just yet, as what we capture right there is arguably the common case.  Instead, I see pre-exec and friends as means to augment that common case, to make special cases possible.

Having said that, I liked @SteVwonder naming of `pre_launch` and `pre_exec`, as it captures the different setup types nicely: `pre_launch` runs before a notion of a rank exists, `pre_exec` runs within rank `0`.  One can make this more complicated, and there are some corner cases for that (`pre_exec_rank`: run something different in all ranks; `pre_exec_node`: run something once per node, etc.) - but `pre_launch` and `pre_exec` should cover the 80% use cases we wanted to target very well.

**Comment by hategan** [comment]
> `pre_exec_rank`: run something different in all ranks; `pre_exec_node`: run something once per node, etc.

Should we maybe leave this to user scripts?

**Comment by hategan** [comment]
Based on the discussion so far, I think there are a couple of questions we should answer before proceeding:

- if a user needs to do PATH=/path/to/my/app:$PATH, should it be required that a pre- script be used?
- how do we specify pre- and post- scripts? As strings that are POSIX shell (or bash maybe?) snippets or paths to executables and perhaps arguments? The latter would be more consistent with the main job specification. Conversely, if the former, should we also have the main job specified in a similar way for consistency?

**Comment by andre-merzky** [comment]
>     * if a user needs to do PATH=/path/to/my/app:$PATH, should it be required that a pre- script be used?
Yes

>     * how do we specify pre- and post- scripts? As strings that are POSIX shell (or bash maybe?) snippets or paths to executables and perhaps arguments? The latter would be more consistent with the main job specification. 

We use an ordered list of strings where the strings are expected to be POSIX shell commands.  I more complex scripts are needed, the user can write shell scripts and source them via `pre_exec` - but we find that this is rarely needed.

> Conversely, if the former, should we also have the main job specified in a similar way for consistency?

I am perfectly happy with executable / arguments / environment.

**Comment by SteVwonder** [comment]
Just to make sure I am on the same page as others, is the idea that:

- Pre-launch we spin up a shell on rank 0 of the allocation with the environment specified in the Jobspec and then source the `pre_launch` script/strings
- Pre-run we run the user-specified parallel launcher using the shell on rank 0 (where it is assumed that the launcher automatically forwards the current environment, or that you can pass flags to make it so) to launch a shell on every rank in the allocation (rank 0 now has 2 shells, one nested within the other).  Those new shells then source the `pre_run` script/strings.
- The shells on each rank run the executable/arguments specified in the jobspec (with the shell doing expansion automatically)
- The shells on each rank source the `post_run` script/strings and then exit
- The original shell on rank 0 sources the `post_launch` script/string and then exits

>> pre_exec_rank: run something different in all ranks; pre_exec_node: run something once per node, etc.

> Should we maybe leave this to user scripts?

I think that makes sense.  Does this mean we need to set env vars or pass arguments to the script to signify what the current rank is within the job/allocation and within the current node?

**Comment by andre-merzky** [comment]
>  Does this mean we need to set env vars or pass arguments to the script to signify what the current rank is within the job/allocation and within the current node?

I would find `JPSI_RANK` env var or (similar) useful (and it's cheap to implement).  

Ack on @SteVwonder summary.  Name change from `pre_exec` to `pre_run` etc was intentional?

**Comment by SteVwonder** [comment]
> Name change from pre_exec to pre_run etc was intentional?

No. Sorry.  Good catch. I'll edit the comment: `sed s/pre_run/pre_exec/g`

**Comment by andre-merzky** [comment]
> > `pre_exec_rank`: run something different in all ranks; `pre_exec_node`: run something once per node, etc.
> 
> Should we maybe leave this to user scripts?
>
>>    Does this mean we need to set env vars or pass arguments to the script to signify what the current rank is within the job/allocation and within the current node?
>
>I would find JPSI_RANK env var or (similar) useful (and it's cheap to implement).

I think we are in agreement that this can be covered by an application wrapper script.  Just want to point out that we (in this case the implementors of J/PSI) could also generate that script, as we have all required information.  Maybe that's for a later stage.
