### ISSUE TITLE
To bulk or not to bulk

### ISSUE THREAD

**Issue by hategan** [ExaWorks/job-api-spec#55]
This issue is here so that we can decide whether to have bulk operations in the API (or not) and, possibly, the extent to which we should have them (i.e., what calls are to also have a bulk version).

There is a long history in the project of scattered discussions on this topic. This issue is meant to gather them in one place.

The starting point was the `submit(Job)` method. It was argued that a `submit(Job[])` bulk version could be useful. The [Bulk Submission Appendix](http://exaworks.org/job-api-spec/specification#appendix-c-bulk-submission) also goes over the details and spells out why bulk calls are unnecessary.

A related discussion is now happening in PR #47. We should move that discussion here.

**Comment by andre-merzky** [comment]
Moving parts of the discussion:



>>    Why do you think they make the interface more complex?

> Because every time the user needs to submit jobs, they need to decide whether to use the bulk or the non-bulk call. If the reason for having a bulk call is that implementations will possibly have better performance if the bulks are used, users will strive to use the bulk call even if they need to submit one job at a time. As I have stated before, we are bleeding implementation details into the API, and we are increasing the cognitive load on the users, but we do so without providing enough information so that the users can make an informed decision. Is it worth it to a user to queue single jobs only to use the bulk call? That can only be answered if the implementation is clear on how efficient the bulk call is vs. the non-bulk call. And it cannot really be answered in general, for all implementations. So, ultimately, our user will probably decide to err on the side of caution and always call the bulk API, implementing a queue if necessary to bulk up single jobs. But this implies that we are failing at design. If we know that this is very likely to happen, we should offset the effort from the user and do this bulking ourselves, so that the bulking code only gets written once. I mean, this is fundamentally what we are doing in this project: writing stuff so that users don't have to each write their own version of said stuff.

> I'll leave bulk exception handling out, but that's an additional complication. It is pretty clear in the current API. The existence of the FaultDetail class is solely due to the bulk exceptions.

>>    I am puzzled by that statement:

```py
    jobs = [make_job() for _ in range(N)]
    for job in jobs:
        jex.submit(job)

    for job in jobs:
        job.wait()
```
>>    vs
```py
    jobs = [make_job() for _ in range(N)]
    jex.submit(jobs)
    jex.wait(jobs)
```
>>    The loops are obvious, but the first also lacks symmetry (submit is on jex, wait is on job). I mean, both are kinda simple of course - but I don't see how bulks add complexity.
>
> I would like to point out that one can have this argument for almost everything: add bulk versions so that users don't have to write for loops. Incidentally, somebody did think this is a great idea to apply universally (see APL)
>
>    Also: the point of bulks is not to make the implementation simpler (it does not), but to make an efficient implementation possible.
>
> I think the bulk submission appendix goes over this. One can queue jobs and periodically drain the queue into an internal bulk submit without exposing that to the user. But there are other ways to do things that can lead to even better performance. An efficient implementation is possible with or without the public bulk methods.
>
> The way bulks can make an implementation easier is by avoiding the aforementioned queue. But it's doing so at the expense of the user who might now have to do write that code themselves.

**Comment by andre-merzky** [comment]
> Because every time the user needs to submit jobs, they need to decide whether to use the bulk or the non-bulk call.

```py
jex.submit(job_instance)
jex.submit(job_list)
```

Nah, not really.  If a user *happens* to have many jobs, they can be passed at once.  For us that is the default use case really - we rarely have applications which create a job now and then, or create different jobs in a loop or something.  It is usually: run 64 k of these, and 10k of those.  Sure, we can loop then, and the loop is trivial, I agree.   But one does throw knowledge away at that point: the bulk will get split up and recreated (to some extent).  

Using threads to queue up to a bulk size or for a bulking time is not great in Python, because, well, threads in Python are not great.  Using processes would involve serialization and de-serialization of the jobs, which for many jobs (which is the case we discuss) is not something I would like to need to do for each submission.

**Comment by hategan** [comment]
> Nah, not really. If a user _happens_ to have many jobs, they can be passed at once.

If it's really that little care that goes in writing software on top of this API, why bother at all? 

Anyway, lack of performance looks like a good reason why a project in and around HPC would fail.

> we do target exascale systems, and we will have to deal with millions of jobs 

I'm really not following any more. Do we or do we not agree that an implementation can bulk requests behind the scenes and route all results to an internal bulk call?

> the following is just simpler

I feel like we're just arguing now. Yes, it is. It is also not a sufficient reason to have a bulk version. If it was, a large majority of methods in lots of standard libraries would have bulk versions.

> It is not about submit only, really. Look at that `wait` line -- how do you implement a global timeout of 3 seconds? Sure, can be done with callbacks: right now we would register a callback `N` times (on `N` jobs), then have a locked list to collect jobs with `DONE` state notifications, and have another thread with a 3 second timer which unregisters the `N` callbacks and then uses that collected list - or something.

```python
left = timeout
for job in jobs:
    start = time.time
    job.wait(timeout=left)
    end = time.time
    left -= end - start
    if left <= 0:
        return # or do whatever needs to be done when a timeout occurs
```

Anyway, I'm not against providing reasonable utilities such as a method to wait on an array of commands.

**Comment by andre-merzky** [comment]
```py
left = timeout
for job in jobs:
    start = time.time
    job.wait(timeout=left)
    end = time.time
    left -= end - start
    if left <= 0:
        return # or do whatever needs to be done when a timeout occurs
```

This makes my point.  If the first job you wait on is running for longer than timeout, the code is no different than 

```py
time.sleep(timeout)
return  # or do whatever needs to be done when a timeout occurs
```

and then you inspect all jobs for their state.

> I feel like we're just arguing now.

probably, and maybe we should stop indeed.  This is all mute without tying the API to explicit use cases.


> Anyway, I'm not against providing reasonable utilities such as a method to wait on an array of commands.

So  why *_are_* we arguing?  Just about if those methods can be bound to the `jex`??

**Comment by hategan** [comment]
> This makes my point.

I am not sure what your point was, but there are no callbacks, additional threads, or locked lists in the code I mentioned.

If your point was that the bulk call was simpler than having to write the wait([]) explicitly, I did not and do not disagree with that, and I have stated so multiple times. It was my understanding, however, that it is not the job of this API to provide various tools to make tying jobs together easier. That's crossing into the realm of workflows.

But then, again, we can explore that possibility. It's all fine, but let's be clear about what are basic goals are. The bulks entered the discussion for performance reasons. We added the argument that it makes it easier for the user to have bulk operations. I disagree that the bulks are necessary for performance, as stated previously. On the other angle, I thought we are going minimal and this seems to contradict that. Again, fine, but we need to decide if we dump minimal and how we decide where to draw lines.

> If the first job you wait on is running for longer than timeout, the code is no different than
> 
> ```python
> time.sleep(timeout)
> return  # or do whatever needs to be done when a timeout occurs
> ```
> 
> and then you inspect all jobs for their state.

I missed that you wanted the done ones returned, but yes.

> > Anyway, I'm not against providing reasonable utilities such as a method to wait on an array of commands.
> 
> So why __are__ we arguing? Just about if those methods can be bound to the `jex`??

No. If they should be part of the spec, which is meant to be focused. They can be part of workflow libraries or even utility classes that are not in the spec, but we provide with the implementation.

**Comment by andre-merzky** [comment]
After discussion on the call, we agreed that bulk versions of the API call will not be part of Layer-0.  We will revisit the discussion after gathering more explicit use cases, and after collecting experience with the layer-0 implementation.
