### ISSUE TITLE
Remove the "have n jobs compete in the queue and keep only the winner" example

### ISSUE THREAD

**Issue by weallcock** [ExaWorks/job-api-spec#57]
In your spec in the appendix you have examples.  This example: https://exaworks.org/job-api-spec/specification#have-n-jobs-compete-in-the-queue-and-keep-only-the-winner should be removed.  It promotes behavior that is generally not considered acceptable at facilities and if users used this behavior it would likely result in censure of some type from the facility.  I am guessing that the example was intending to demonstrate some aspect of how the API could be used or address some requirement, but this example is **NOT** the one I would suggest to communicate that.

**Comment by Larofeticus** [comment]
I'm curious what use was in mind that put that example there.

At any single site/single machine the outcome is going to be which ever job was submitted first in the group starts first.
Maybe if there are multiple machines with independent queues? Definitely if there are independent sites.
But referring to independent queues and sites as "N jobs" is weird use of terms.

Is this computer science brain probing for edge cases?

**Comment by hategan** [comment]
> I'm curious what use was in mind that put that example there.

Just wanted to mention that I am not answering the above.

> At any single site/single machine the outcome is going to be which ever job was submitted first in the group starts first.

If the number of nodes for each job is the same, maybe so, but I doubt this is generally true. A large job is probably going to be queued for longer than a small job. That and multiple clusters.

> Maybe if there are multiple machines with independent queues? Definitely if there are independent sites.
> But referring to independent queues and sites as "N jobs" is weird use of terms.

I don't think a good workflow system should care where those jobs are run. So I am a bit surprised that what needs to run would be called weird based on where it runs.

Anyway, I don't think much is lost from a pedagogic perspective is this example was removed.
