### ISSUE TITLE
Document Best Practices (probably separate doc)

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/job-api-spec#59]
On the Tuesday call, there was a suggestion to have a "clippy-style assistant" that can alert users when they are using the API in a way that it detrimental to their or the system's performance (e.g., submitting 1 million individual jobs into a queue as opposed to using a pilot job).

Whether or not we end up implementing any sort of intelligent agent to detect bad behavior and provide recommendations, we should certainly document best practices for using the API.  This best practices document (which would probably be separate from the J/PSI specification) could serve as a useful guide to users as-is, and down the road potentially serve as the basis for any intelligent agent's detection mechanisms and recommendations.

**Comment by hategan** [comment]
Out of scope for the api specification.
