### ISSUE TITLE
Add a `executor.list()` method on the executor

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#69]
This is related to PR #68 

**Is your request related to a problem? Please describe.**
The API includes an `executor.attach()` method which can be used to re-attach to a running (or at least known) job instance.  However, the API misses means to list known job instances.

**Describe the solution you'd like**
Add an `executor.list()` method to return the IDs of known job instances which the API can attach to.

**Describe alternatives you've considered**
IDs can be retrieved out of band, which seems an impractical solution to me.

**Additional context**
Independent from the `list()` proposal above:
The API handles two types of job IDs: the native job ID as assigned by the underlying LRM system, and the native job ID as assigned by the J/PSI implementation.  Those IDs may or may not be the same.  `list()` should return the native IDs of the job.  Further, the document should clarify the scope of J/PSI IDs.  For example, if one attaches two job instances to the same native job ID, will that result in the same J/PSI ID?  If not, what is the exact purpose of the J/PSI ID?  If yes, can the native ID and the J/PSI ID be used interchangeably?

**Comment by andre-merzky** [comment]
I added the January milestone to obtain clarity on the JobID (not necessarily on the `list()` method).

**Comment by SteVwonder** [comment]
From @hategan in #68:

> I think list() is not needed to address short-lived clients, so it is my suggestion that we keep/discuss list() separately.

@hategan: could you expand on your thoughts regarding `list()` in this thread?

**Comment by hategan** [comment]
> > I think list() is not needed to address short-lived clients, so it is my suggestion that we keep/discuss list() separately.
> 
> @hategan: could you expand on your thoughts regarding `list()` in this thread?

It is my understanding that `getId()` combined with `attach()` addresses the original request. I think we should expedite integrating that.

There are questions I have about `list()`. It's meant to return all jobs belonging to a user, regardless of whether they were launched through some specific instance of JPSI or not (or even JPSI at all). I mean, it's not not useful. But maybe there are some subtleties there that we might want to ponder about without holding the doc hostage.

**Comment by andre-merzky** [comment]
> There are questions I have about `list()`. It's meant to return all jobs belonging to a user, regardless of whether they were launched through some specific instance of JPSI or not (or even JPSI at all).

I consider it an equivalent of `qstat -u <user_id>`.  

>  I mean, it's not not useful.

It provides the list of job IDs the API is able to attach to.  Those IDs are otherwise only be available out of band.  I don't insist on adding `list()`, but yes, I do find it useful.

>  But maybe there are some subtleties there that we might want to ponder about without holding the doc hostage.

It's not my intent to hold the doc hostage.  #81 is open for review now which only adds `attach()` and `get_native_id()`, which reduces #68 to adding `list()` (renamed).

**Comment by hategan** [comment]
> 
> > I mean, it's not not useful.
> 
> It provides the list of job IDs the API is able to attach to. Those IDs are otherwise only be available out of band. I don't insist on adding `list()`, but yes, I do find it useful.

The double "not" was not a typo. I.e., `not(not(x))`. Although the meaning is not quite the same as `x`.

> 
> > But maybe there are some subtleties there that we might want to ponder about without holding the doc hostage.
> 
> It's not my intent to hold the doc hostage. #81 is open for review now which only adds `attach()` and `get_native_id()`, which reduces #68 to adding `list()` (renamed).

I'm not trying to say you are doing something bad. I'm trying to find ways to make progress.

**Comment by andre-merzky** [comment]
> The double "not" was not a typo. I.e., `not(not(x))`. Although the meaning is not quite the same as `x`.

Apologies, my parser got impacted by the holidays or something.


> I'm not trying to say you are doing something bad. I'm trying to find ways to make progress.

No worries, acknowledged and appreciated :-)

**Comment by hategan** [comment]
So...

The API was, in my mind at least, something used to submit jobs and manage *those* jobs. `list()` would not be necessary there (A).

On the other hand, the are places where the API is touted as an abstraction over LRMs and that abstraction would be awfully broken without `list()` (B).

We should decide between (A) and (B). If (B), then may I suggest making sure that the following are made clear:
- the returned list is one of native IDs
- there is no simple relationship between jobs submitted through this API and the list returned by `list()` (other jobs may be there, some jobs submitted through the API may not be returned by `list()`, etc.)

**Comment by andre-merzky** [comment]
I am in favour of (B) (as the ticket shows I guess).

> some jobs submitted through the API may not be returned by `list()`,

Why not so?  I would expect `list()` to return at least all identifiers for jobs whose information are not yet purged in the backend or in the J/PSI implementation, so at least for all non-final jobs.  


> the returned list is one of native IDs

I am ok with that, but still would like clarification on the relation between native IDs and J/PSI IDs.  I would assume that we can sue the native ID to re-attach to a job (otherwise they would not be very useful I think) - but also, shouldn't we be able to re-attach to a J/PSI ID?  Will attaching twice to the same native IDs result in job objects with the same J/PSI ID?  I don't necessarily have answers, but would find it useful if we get clarity on those questions before we settle on what `list()` returns.

**Comment by hategan** [comment]
> I am in favour of (B) (as the ticket shows I guess).
> 
> > some jobs submitted through the API may not be returned by `list()`,
> 
> Why not so? I would expect `list()` to return at least all identifiers for jobs whose information are not yet purged in the backend or in the J/PSI implementation, so at least for all non-final jobs.

Right. The ones purged would not be there. That's the point. You may have Job objects in a final state for which `list()` would not return a native ID. So, morally, `list()` lives in a very different region than the rest of the API.

> 
> > the returned list is one of native IDs
> 
> I am ok with that, but still would like clarification on the relation between native IDs and J/PSI IDs. I would assume that we can sue the native ID to re-attach to a job (otherwise they would not be very useful I think) - but also, shouldn't we be able to re-attach to a J/PSI ID?

Multiple reasons why we shouldn't use normal IDs for this:
- the native ID already provides a solution here; not sure why we'd want another solution for the same problem
- what does it even mean to attach to a non-native ID? say you shut everything down and only remember the ID, what meaning would that have in a new process with no additional context? You may get away with this in the same process, by keeping an `ID -> nativeID` mapping, but otherwise the ID is a random string.
- the more pertinent question isn't "why not", but "why"? In order to avoid scope creep, we should have to justify what we include not what we exclude.

> Will attaching twice to the same native IDs result in job objects with the same J/PSI ID?

Why would it? A job that isn't attached has an ID and that ID should not change when the job is attached, otherwise it's not much of an ID.

> I don't necessarily have answers, but would find it useful if we get clarity on those questions before we settle on what `list()` returns.

**Comment by andre-merzky** [comment]
> > > some jobs submitted through the API may not be returned by `list()`,
> > 
> > 
> > Why not so? I would expect `list()` to return at least all identifiers for jobs whose information are not yet purged in the backend or in the J/PSI implementation, so at least for all non-final jobs.
> 
> Right. The ones purged would not be there. That's the point. You may have Job objects in a final state for which `list()` would not return a native ID. So, morally, `list()` lives in a very different region than the rest of the API.

If the API still knows about job, then they are not purged, and the native ID can be inspected.  Or am I missing something?

> > Will attaching twice to the same native IDs result in job objects with the same J/PSI ID?
> 
> Why would it? A job that isn't attached has an ID and that ID should not change when the job is attached, otherwise it's not much of an ID.

Fair, also on attaching J/PSI IDs.

**Comment by hategan** [comment]
> If the API still knows about job, then they are not purged, and the native ID can be inspected. Or am I missing something?
> 

That would imply that the executor should maintain a list of jobs even after they complete. We'd need to document that, since it would be a memory leak, and/or provide means to purge these jobs. Alternatively, we could require the implementations to maintain weak references to said jobs, such that they're only guaranteed to be returned by `list()` if a strong reference is kept to the jobs in user code, although this implies a garbage-collected system. It's just getting very hairy for a feature that has no user request or use case.

**Comment by andre-merzky** [comment]
> > If the API still knows about job, then they are not purged, and the native ID can be inspected. Or am I missing something?
> 
> That would imply that the executor should maintain a list of jobs even after they complete. We'd need to document that, since it would be a memory leak, and/or provide means to purge these jobs. Alternatively, we could require the implementations to maintain weak references to said jobs, such that they're only guaranteed to be returned by `list()` if a strong reference is kept to the jobs in user code, although this implies a garbage-collected system. It's just getting very hairy for a feature that has no user request or use case.

I may parse this incorrectly, apologies.  I see these options:

 - a job is not completed: the backend should still list it, and so should J/PSI (from cache or by inspecting the backend)
 - a job is completed
   - it is purged in backend and J/PSI: list does not show
   - it is purged by J/PSI but not backend: list can show via inspecting backend
   - is is purged by backend but not by J/PSI: list can show job from local knowledge

**Comment by hategan** [comment]
> I may parse this incorrectly, apologies. I see these options:

Yes. In order:
* not completed: not problematic
* completed:
  * purged by both: user code can still hold refs to jobs, so "some jobs submitted through the API may not be returned by list()"
  * purged by J/PSI: same as above
  * purged by backend: if we want to return these through list(), we need a ref to them from the executor, so this is the discussion immediately above
  * purged by neither: also not problematic

**Comment by andre-merzky** [comment]
From discussion on the call: we agree on that list of possibilities.  An implementation may purge job information for which the application still owns handles, and those jobs would then not be listed if they are also purged from the backend (and thus in final state).  That seems acceptable.
