### ISSUE TITLE
Language-Agnostic Specification?

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/job-api-spec#71]
This is an issue to track how me might be able to specify the standard in a more language-agnostic way, and whether we want to go that route (conversation originally started in #26).  If we do, then presumably, we would have language-specific API documents that accompany the agnostic standard document.

If we decide to continue using specific languages in the standard, maybe we should consider something like what zeromq does in their [Guide](https://zguide.zeromq.org/docs/chapter2/#Handling-Multiple-Sockets) (provide each example in multiple language inline in the doc)

**Comment by andre-merzky** [comment]
> This is an issue to track how me might be able to specify the standard in a more language-agnostic way, and whether we want to go that route (conversation originally started in #26). If we do, then presumably, we would have language-specific API documents that accompany the agnostic standard document.

One common option is the [Interface Description Language (IDL)](https://en.wikipedia.org/wiki/Interface_description_language).  Several OGF specs used that (in different forms), including SAGA.  I like that option.


> If we decide to continue using specific languages in the standard, maybe we should consider something like what zeromq does in their [Guide](https://zguide.zeromq.org/docs/chapter2/#Handling-Multiple-Sockets) (provide each example in multiple language inline in the doc)

I also like that option - the ZMQ doc is really a great example in that respect.  That would imply though that we **have** the respective language bindings.  Which is not a bad thing possibly ;-)

**Comment by SteVwonder** [comment]
> I also like that option - the ZMQ doc is really a great example in that respect.

Per this option, it sounds like @hategan has an idea in mind for making this work in the current document with some javascript magic.

**Comment by andre-merzky** [comment]
Also, we can actually apply both: have the specification part in IDL (or similar), **and** examples for different languages.

**Comment by hategan** [comment]
@andre-merzky Any specific IDL you have in mind?

For reference, I opted for a C++/Java like syntax because it's common and generally more formal than Python. I would suspect most people in the field would be familiar with what it says.

I can experiment with a ZMQ-like language tab switcher that renders as a sequence in plain MD and let you know.

**Comment by andre-merzky** [comment]
> For reference, I opted for a C++/Java like syntax because it's common and generally more formal than Python. I would suspect most people in the field would be familiar with what it says.

Yeah, I figured, and I certainly appreciate that!  


> @andre-merzky Any specific IDL you have in mind?

IDL itself was created (to my knowledge) in the context of Corba, and as such is [specified](https://www.omg.org/spec/IDL/4.2/PDF) by the [Object Management Group (OMG)](https://www.omg.org/).  I mostly looks like a subset of C++ anyway:

```cpp
interface A {
  typedef long L1;
  short opA (in L1 l_1, out L1 l_2);
};
interface B {
  typedef short L1; 
  L1 opB (in long l);
}; 
interface C: B, A {
  typedef A::L1 L3; 
  B::L1 opC (in L3 l_3);
```

For SAGA (and some other OGF specs) we used LLNL's [Babel/SIDL](https://computing.llnl.gov/projects/babel-high-performance-language-interoperability/) - have a look a [these slides](https://computing.llnl.gov/projects/babel-high-performance-language-interoperability/docs/cca-030410-dbc1.pdf) for an overview.  It worked well for us, although we did not follow it to the letter.

**Comment by hategan** [comment]
I've added a CSS/JavaScript thing for this. I apologize for doing without a PR, but GH pages is set up to work with a single branch (main at the moment).

The basic idea is this:
````html
<div class="lang-tabs">
C++:

```C++
// C++ code here
```
Python:

```python
# python code here
```
</div>
````

The empty lines after the labels are not necessary, but it makes at least one editor preview plugin render things better.

Relevant javascript then takes the labels, removes the trailing colon, and converts them into tab labels, while adding all the necessary tabbing stuff. You can see the end result at https://exaworks.org/job-api-spec/specification.html#jobexecutor

**Comment by andre-merzky** [comment]
This is really neat!

**Comment by hategan** [comment]
Using an IDL-like language may not be as useful at this time. The ability to have code examples in multiple languages may be a better solution and conveying things that are not language specific.
