### ISSUE TITLE
How to initialize a J/PSI Connector

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/job-api-spec#72]
There was a discussion of how to initialize a particular J/PSI connector. 

Should the connector be stateful or stateless?  What are the pros and cons of each?  Once we determine that, then we should decide what the initialization should look like (e.g., factory, class constructor, etc).

This is the main issue blocking the prototype in https://github.com/ExaWorks/jpsi-python/pull/2 from being standards-compliant.

**Comment by hategan** [comment]
I tried to write an "abstract" version of what follows, but I think it ends up more being unnecessarily obscure. So I'll try simple sentences and not that much abstraction.

We need to do two things, which, from a certain distance, can be seen as one:
A. Instantiate a connector
B. Configure a connector

There are probably more ways to do this, but here are a few that I can think of:
1. JobExecutor is a base class and we use constructors to instantiate connectors, which are subclasses of JobExecutor:
    - `e1 = PBSJobExecutor(); e2 = SLURMJobExecutor()`
    - there are some possible ways to do (B):
        1. By passing configuration parameters to a constructor:
            - `e3 = FluxJobExecutor(endpoint1); e4 = FluxJobExecutor(endpoint2)`
        2. By using an initialization method:
            - `e5 = FluxJobExecutor(); e5.initialize({endpoint: endpoint1}); e6 = FluxJobExecutor(); e6.initialize({endpoint: endpoint2})`
        3. As part of the job specification:
           - `e7 = FluxJobExecutor(); j1.setEndpoint(endpoint1); j2.setEndpoint(endpoint2); e7.submit(j1); e7.submit(j2);`
2. JobExecutor is a base class, but we use a factory to instantiate connectors; this can coexist with (1):
    - `e8 = JobExecutorFactory.getInstance("PBS"); e9 = JobExecutorFactory.getInstance("SLURM")`
    - (B):
        1. Pass configuration parameters to the factory:
            - `e10 = JobExecutorFactory.getInstance("Flux", endpoint1); e11 = JobExecutorFactory.getInstance("Flux", endpoint2);`
        2. Using an initialization method once we get a (new) instance through the factory
        3. As part of the job spec, as above
3. JobExecutor (or something that implements the JobExecutor interface) is a frontend and it is its own business what it does behind the scenes:
    - `e12 = JobExecutor("PBS"); e13 = JobExecutor("SLURM")`
    - factories make little sense here
    - this looks like an obvious choice if an existing library is adapted to the JPSI API (i.e., SAGA -> JPSI)
    - configuration can be done similarly to the other cases:
        1. Parameters passed to the constructor:
            - `e14 = JobExecutor("Flux", endpoint1); e15 = JobExecutor("Flux", endpoint2)`
            - this is where one could combine the name of the connector with the endpoint into a URL: `e16 = JobExecutor("flux://localhost:1234")`
        2. An initialization method, which works like it did in the previous examples
        3. In the job spec, again, as above

Let me know if there are other ideas. We may want to look at the benefits/downsides of each combination.

**Comment by andre-merzky** [comment]
Sorry for replying late.  

Here is another option which probably belongs to (3):
```py
import flux.psi.j as jpsi
executor = jpsi.JobExecutor(...)
```

This leaves the class names unchanged between implementations and thus increases source code compatibility, which is something we seem to aim for.  Specifically for Python this is frequently used, but other standardized APIs also strive for that type of compatibility.

As for delayed initialization like
```py
e5 = FluxJobExecutor()
e5.initialize({endpoint: endpoint1})
e6 = FluxJobExecutor() 
e6.initialize({endpoint: endpoint2})
```

I don't like that much: it provides no benefit (that I can see) compared to passing the arguments directly to the constructor, and requires additional clarification on what happens on repeated initialization, and also on how the class instance behaves between construction and initialization: it basically creates two states for the executor, `UNITIALIZED` and `INITIALIZED`.

**Comment by hategan** [comment]
> This leaves the class names unchanged between implementations and thus increases source code compatibility, which is something we seem to aim for.

Inheritance achieves the same goal. So we should be careful not to suggest that the above is the only solution to this problem.

> I don't like that much: it provides no benefit (that I can see) compared to passing the arguments directly to the constructor,

I agree. We should probably cross it out.

**Comment by andre-merzky** [comment]
> So we should be careful not to suggest that the above is the only solution to this problem.

The statement was:

> Here is another option which probably belongs to (3):

I don't see how that would imply that this would be the only solution -- clearly all options you list do work.  The argument I am making for this is that is does provide source compatibility, and that it is not a surprising approach given that it is a common approach in other modules / standards (that includes the ones I have been working with in the past).

> Inheritance achieves the same goal

it _can_ achieve the same.  Inheritance as in (1):
```py
je = PBSJobExecutor()
```
requires to change code to
```py
je = SlurmJobExecutor()
```
when switching backends.

Parameterized factories avoid that, but I still have not heard a compelling argument which makes factories preferable to simple parameterized construction, also in the context that factories are not a really common pattern in Python.

So, from the 3 main options you list above, I do indeed prefer number (3), for the reasons stated.

**Comment by andre-merzky** [comment]
@hategan , @SteVwonder : I propose to take this out of the alpha release.  We did agree (I think) that the constructor specification and parameterisation is a language binding issue and thus does not need to be added into the spec at this point.

**Comment by hategan** [comment]
> I propose to take this out of the alpha release. 

I agree.

> We did agree (I think) that the constructor specification and parameterization is a language binding issue and thus does not need to be added into the spec at this point.

I'd go further in that it may very well be an implementation preference. Which is why I'd put it in the spec. But I don't think we'll make progress here any more, so it seems wise to postpone this discussion for now.

**Comment by hategan** [comment]
The specification does not prescribe a way of getting instances of executors. This is left to implementations to do as it makes sense for the language that they implement in.

Furthermore, the reference python implementation allows both direct instantiation and a factory. 

So this is partially done, but as much as we are willing to push it.
