### ISSUE TITLE
Constructors for JobSpecification and ResourceSpecification classes

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#75]
In the context of the Python prototype implementation we began to [discuss](https://github.com/ExaWorks/jpsi-python/pull/2/files#r546603797) constructors for the Specification classes - those do not yet define constructors.  This issues moves that discussion to the specification scope.

**Comment by hategan** [comment]
I would say that the "canonical" way to work with these objects should be:

```python
spec = JobSpecification()
spec.<property> = <value>
...
```

I think @andre-merzky has provided some examples in the doc that used the following scheme:

```python
spec = JobSpecification({<propname>: <value>...})
```

For Python, I would, instead, suggest using keyword arguments:
```
spec = JobSpecification(<propname>=<value>...)
```

However, I do not see either the dictionary or the keyword args as a language-agnostic solution, since many languages do not have nice dictionary initializers or keyword arguments. So perhaps this should be left out of the core spec and moved into a language binding doc.

**Comment by andre-merzky** [comment]
> However, I do not see either the dictionary or the keyword args as a language-agnostic solution, since many languages do not have nice dictionary initializers or keyword arguments.

I don't see this as language agnostic either.  Sorry for not replying to your comment on the example PR, but I don't mind changing the Python examples to the canonical way above and to leave other language specific initializers to the language binding.

**Comment by andre-merzky** [comment]
For the Python bindings, we do use dict initializers successfully, and we and our users find it convenient to use for two main reasons:

  - it is easy to read a task spec from a json file or similar and directly create an task object specification from it
  - it is easy to use a dictionary template and to create a large number of task objects with minor parametrization
 
Non-dict initializers provide the same semantics, but dict initializers lead to simpler code, which is good.

As for type safety: Python is finally moving to [typed dicts](https://www.python.org/dev/peps/pep-0589/), but meanwhile we have our own [implementation](https://github.com/radical-cybertools/radical.utils/blob/devel/src/radical/utils/munch.py) of a typed dictionary which is actually [faster](https://github.com/radical-cybertools/radical.pilot/blob/devel/docs/architecture/dicts/README.md) than the mypy implementation of the above, and allows for runtime type checking and conversion (vs. static type checking).  This is just to say I am confident this is implementable, save, fast and increasingly mainstream.  Thus my proposal for the Python language binding is to allow 2 forms of initialization:

  - canonical:
```py
spec = jspi.JobSpec()
spec.<property> = <value>
...
```
  - dict based:  
```py
spec = jspi.JobSpec({
    <property> : <value>
    ...
    })
```

I see some disadvantages for keyword arguments: it becomes unwieldy for large numbers or properties, and even more so for non-trivial value data types such as the `resourceSpec`.  FWIW, the latter is where a dict initializer is also simpler to use than the canonical initializer:

```py
# canonical
jspec = jspi.JobSpec()
jspec.executable = 'date'

rspec = jpsi.ResourceSpec()
rspec.cores = 1

jspec.resources = rspec


# dict based:  
jspec = jspi.JobSpec({
    'executable' : 'date', 
    'resources'  : {'cores' : 1}
})

**Comment by hategan** [comment]
> Non-dict initializers provide the same semantics, but dict initializers lead to simpler code, which is good.

I don't see much difference on the user's side between `JobSpec({...})` and `JobSpec(**{...})`. And I don't see the benefit of typed dicts over keyword args for the following reason: if you have to declare types for every kv pair, you have to spell those keys and types out, same as for keyword args. Additionally, keyword args are 1) designed and used for this situation and 2) a stable and well established feature of the language.

**Comment by andre-merzky** [comment]
`Spec(**{...})` does not help with hierarchies (e.g., a resource spec as property of a job spec).  And yes, one has to type things out either way, I don't think saving keystrokes is an advantage of either.

**Comment by hategan** [comment]
> `Spec(**{...})` does not help with hierarchies (e.g., a resource spec as property of a job spec). And yes, one has to type things out either way, I don't think saving keystrokes is an advantage of either.

`f(a=1, **{'b': 2})` is equivalent to `f(**{'a': 1, 'b': 2})` so I think one can say 
```python
JobSpec(**{...}, resourceSpec=ResourceSpec(**{..}))
```

or any other variation on this theme.

**Comment by andre-merzky** [comment]
> `JobSpec(**{...}, resourceSpec=ResourceSpec(**{..}))`

Yes, I think I said 'simpler code' somewhere :-)

```py
jspec = jspi.JobSpec({
    'executable' : 'date', 
    'resources'  : {'cores' : 1}
})
```
vs. 

```py
jspec = jspi.JobSpec(**{
    'executable' : 'date', 
    'resources'  : jpsi.ResourceSpec(**{'cores' : 1})
})
```

I don't honestly know a single API which would encourage `**` for dict based initialization (even though it works, obviously), and have never used it myself- did you?

**Comment by hategan** [comment]
> I don't honestly know a single API which would encourage `**` for dict based initialization

I think something got lost in translation somewhere :)
- for your example, you'd use
    ```python
   jspec = JobSpec(executable='date', resources=ResourceSpec(cores=1))
    ```
- if you needed to construct a JobSpec from a pre-built dictionary `dict`, such as your scenario of reading from a json file, you would use `jspec = JobSpec(**dict)`

**Comment by andre-merzky** [comment]
>     * if you needed to construct a JobSpec from a pre-built dictionary `dict`, such as your scenario of reading from a json file, you would use `jspec = JobSpec(**dict)`

As said, this does not work for this case:
```py
jspec = jspi.JobSpec({
    'executable' : 'date', 
    'resources'  : {'cores' : 1}
})
```
as the `resources` value would need a cast to `jpsi.ResourceSpec`.

**Comment by hategan** [comment]
> As said, this does not work for this case

1. the JobSpec constructor can check if dict and wrap in ResourceSpec
2. If we want to add serialization to our objects, we should probably not do it in an ad-hoc way, piggybacking on other issues.

**Comment by andre-merzky** [comment]
> > As said, this does not work for this case
> 
>     1. the JobSpec constructor can check if dict and wrap in ResourceSpec

So we do transparent conversion from dict to spec in the sub-dict, then why not for the dict itself?
 
>     2. If we want to add serialization to our objects, we should probably not do it in an ad-hoc way, piggybacking on other issues.

I am not exactly sure where serialization comes in.  This is only about *initialization*, isn't it?

PS.: It seems we rarely manage to discuss anything without exchanging at least 20 comments back and forth... :-/

**Comment by hategan** [comment]
> So we do transparent conversion from dict to spec in the sub-dict, then why not for the dict itself?

We could. I'm not sure how useful it is to do so only to save the user writing two stars, but that's another story.

> I am not exactly sure where serialization comes in. This is only about _initialization_, isn't it?

You said in the beginning that initializing from a dict is useful when you want to construct many objects from json data. That's de-serialization.
