### ISSUE TITLE
naming consistency for specification classes

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#76]
we use `JobSpecification` and `ResourcesSpec` - note the singular/plural difference, and the full name / short name.  I suggest to make this consistent with `JobSpecification` and `ResourceSpecification`.  

As argument for singular: It is customary to use singular in class names even when the can handle multiple entities, like `JobExecutor`, not `JobsExecutor`, `FileManager`, not `FilesManager`, etc.

**Comment by hategan** [comment]
The plural is confusing. I'm on board with `ResourceSpecification`.
