### ISSUE TITLE
- [ ] "canceled" or "cancelled"?   

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#9]
data point:  SAGA uses "CANCELED" as job state, FWIW, as does the whole RCT stack.

**Comment by jameshcorbett** [comment]
I vote canceled, since American English is what I imagine the entire computer science community is accustomed to: https://www.merriam-webster.com/words-at-play/canceled-or-cancelled. But of course I would take this back if popular software could be found that used "cancelled."

**Comment by tgamblin** [comment]
+1 for "canceled"

**Comment by andre-merzky** [comment]
Thanks all - we agreed on `CANCELED` and changed the document.
