### ISSUE TITLE
Override Environment

### ISSUE THREAD

**Issue by andre-merzky** [ExaWorks/job-api-spec#93]
The spec states:
```
If this flag is set to `false`, the job starts with an empty environment.
The only environment variables that will be accessible to the job are the
ones set using `setEnvironment()`. If this flag is set to `true`, which
is the default, the job will also have access to inherited environment
variables. The precise nature of the inherited environment is left to the
implementation. In principle, this functionality is meant to allow
computing resources to pass various information to executing
applications, such as the location of a scratch directory in `$SCRATCH`,
while still allowing clients to define unrelated environment variables
```

I cannot reconcile my concept of `environment` with this statement, specifically with `If this flag is set to 'true', which
is the default, the job will also have access to inherited environment variables.`.  What is that supposed to convey?  Either the environment is empty, or it is not -- how is an `access to inherited environment variables` expected to look like if exactly that environment is purged per this flag?

I see another issue: what about env settings which are required by, say, MPI - those cannot possibly be set by the user.  Would setting the `flag` to `True` disable all MPI tasks?

I would suggest two changes:

  - keep the literal meaning of the flag: the original env is purged, the specified env replaces (overrides) it.
  - make the default `False`: getting env settings correct is not trivial, and the default env settings on a cluster (as determined by admins, batch system and launchers) is usually a good starting point for any application.

**Comment by hategan** [comment]
> What is that supposed to convey? Either the environment is empty, or it is not

I'm not entirely sure what you are asking. There is an inherited environment and an environment defined by the spec. This flag controls whether the inheritance happens (or, if you want, whether the inherited environment is empty or not).

The term "override" is to be understood in the OOP sense. If you "override" a class, the subclass also has the parent's class methods. If you do not "override" any class, the subclass only has the methods that you define for it.

That said, I'm happy to rename "overrideEnvironment" to something else that is less confusing.



> I see another issue: what about env settings which are required by, say, MPI - those cannot possibly be set by the user. Would setting the `flag` to `True` disable all MPI tasks?

That needs to be clarified: this flag does not apply to JPSI (launcher) defined variables

**Comment by andre-merzky** [comment]
Well, the text states:

> If this flag is set to `false`, the job starts with an empty environment.

There is no mentioning of an *inherited* environment, but of an *empty* environment - which would mean that no env variables are set whatsoever.  If that is not what that sentence is supposed to say, then the language should probably be changed or the statement should be clarified.  Can you help me understand that part?  My other remarks work from that premise, so may be invalid after all...

**Comment by hategan** [comment]
>> If this flag is set to `false`, the job starts with an empty environment.
> Can you help me understand that part?

I think what's implied there is that "... after which what's declared using setEnvironment() is applied...". So I think the idea is:

1. Start with either empty env or whatever the LRM starts the "naked" job with; this is the part decided by `overrideEnvironment`
2. apply global JPSI variables
3. apply what `setEnvironment()` has
4. apply rank JPSI variables

But I see what you mean now. The description is poorly written. We should fix this.

**Comment by andre-merzky** [comment]
> `start with either empty env or whatever the LRM starts the "naked" job with`

The first part is what I worry about: starting with an empty env (nothing is set) is not something I would consider useful - in most cases I can think of that would simply prevent the workload from working (no `module load`, no `$SCRATCH`, no `sh` or any other unix tool, etc), or place a significant burden onto the user to find out what env is needed to set up to get it to work (what is the module path?  Do I need `/usr/local/bin`?  What are the shared file systems?).  If you have use cases which need that, then sure - but I would like to ask to not make this the default case.

**Comment by hategan** [comment]
> The first part is what I worry about: starting with an empty env (nothing is set) is not something I would consider useful

Useful or not, it is what `execve()` does. I'd also argue that in some cases where "reproducible" is a keyword, one might want to define exactly what everything is and nothing else. So I'd keep it, document it, and not have it used by default (i.e., please note that this is NOT the default).

**Comment by andre-merzky** [comment]
Do you have a use case?  `Useful or not` is exactly my point - I'd rather not include things which are not at least a bit useful.  I don't know any launcher which would me allow to implement `execve` semantics (apart from wrapping the task in a script doing `unset`/`set` for all env vars).

Anyway, that's my last reply, let's not drag this out again.  We seem to have a hang for that...

**Comment by hategan** [comment]
> Do you have a use case

Yes, the reproducible jobs, where I don't want random environment variables which may change from one invocation to the other to be there.

> don't know any launcher which would me allow to implement `execve` semantics

`env - ...`

`mpirun -(g)envnone ...`

`srun --export=NONE ...`

(although subtleties exist)

> let's not drag this out again.

Agreed, but I think we still want to make the text clear. So, if nothing else, let's drive that nail through.

**Comment by andre-merzky** [comment]
Thanks for the examples, that helps.

**Comment by SteVwonder** [comment]
> That said, I'm happy to rename "overrideEnvironment" to something else that is less confusing.

Would it be clearer to rename the flag to "inheritEnvironment"?  Where the semantics are the same as it is now (e.g., `true` means that you start with the "inheritted env" and `false` means that you start with an empty env).

**Comment by hategan** [comment]
> Would it be clearer to rename the flag to "inheritEnvironment"?

Yes, I think so. That would have been my proposal, but I was waiting to see what other options there might be.
