### ISSUE TITLE
Consider adding IllegalStateException to submit() and cancel()

### ISSUE THREAD

**Issue by hategan** [ExaWorks/job-api-spec#99]
**Is your request related to a problem? Please describe.**
It is possible for clear violation of the basic assumed job submission workflow to occur, such as calling `submit()` twice on a job, or attempting to `cancel()` a job that has not yet been submitted. There should probably be a separate exception to signal such situations.

**Describe the solution you'd like**
Have issues such as above trigger a `IllegalStateException` or `InvalidStateException`.

**Describe alternatives you've considered**
Without adding an exception, situations like these would have to trigger a `SubmitException`. However, the nature of the exceptional situation seems fundamentally different than what `SubmitException` appears to be designed for.

**Comment by andre-merzky** [comment]
I agree with the request.  

> IllegalStateException or InvalidStateException

slight preference for the latter.  Consider calling `cancel()` on a `NEW` job: the `NEW` state is not illegal, but invalid for the call.

**Comment by hategan** [comment]
> [...] 
> > IllegalStateException or InvalidStateException
> 
> slight preference for the latter. [...]

It's a pre-defined exception in Java whose doc says: "Signals that a method has been invoked at an illegal or inappropriate time. In other words, the Java environment or Java application is not in an appropriate state for the requested operation."

I don't care in particular about the name. I would expect that if the stdlib of a language already has an exception for this purpose, that an implementation would use it instead of re-inventing the wheel, so I'd assume that `IllegalStateException` would still be used by Java implementations, whether the spec mentions one or the other.

**Comment by andre-merzky** [comment]
I see, thanks for the information.  Then I also don't mind either way really.

**Comment by hategan** [comment]
> I see, thanks for the information. Then I also don't mind either way really.

I guess we could go deeper and figure out which one might be better. I.e., whether we want to maximize re-use of existing language infrastructure at the expense of uniformity across languages or have things closer to a unified spec.

**Comment by andre-merzky** [comment]
As long as the gist (the semantics) is clear, I have no problems whatsoever to leave the actual exception type choice to the language binding, to be close to what a user would expect in that language.  I'm afraid that Python does not have a suitable native exception either way, so it would boil down to a `RuntimeError`, or we create a custom exception (inherited from `RuntimeError` or `BaseException`), so I don't mind staying close to what is well defined in Java.  Happy to leave this to your liking here.
